### ISSUE TITLE
Search function generates an Attribute Error

### ISSUE THREAD

**Issue by cedricviaccoz** [halcy/Mastodon.py#100]
Apparently whenever I try to search, I get this error : 
`Traceback (most recent call last):
  File "MapBot.py", line 133, in <module>
    main(sys.argv)
  File "MapBot.py", line 27, in main
    geopulses = Mastodon.search(HASH_MARKER, False)
  File "/anaconda3/lib/python3.6/site-packages/mastodon/Mastodon.py", line 436, in search
    params = self.__generate_params(locals())
AttributeError: 'str' object has no attribute '_Mastodon__generate_params'
`
I've logged in myself before calling search, and the value of HASH_MARKER is "#geoCoords" but I've tried with different strings and it produced the same error.

**Comment by halcy** [comment]
Are you sure you are using the current version of Mastodon.py? The lines seem wrong (Line 436, in my repo version, is a comment), and I cannot reproduce the Problem. The conda package may be outdated - I do not maintain it myself.

Try installing the version from pip and tell me if that helps, please.

**Comment by cedricviaccoz** [comment]
Effectively, I was on the 1.1.1 version, I've uninstalled it, and reinstalled the 1.1.2 version by pip, but it still does put some of those file in anaconda3, 

'''
 pip install Mastodon.py
Collecting Mastodon.py
  Using cached Mastodon.py-1.1.2-py2.py3-none-any.whl
Requirement already satisfied: requests in /anaconda3/lib/python3.6/site-packages (from Mastodon.py)
Requirement already satisfied: six in /anaconda3/lib/python3.6/site-packages (from Mastodon.py)
Requirement already satisfied: pytz in /anaconda3/lib/python3.6/site-packages (from Mastodon.py)
Requirement already satisfied: python-dateutil in /anaconda3/lib/python3.6/site-packages (from Mastodon.py)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /anaconda3/lib/python3.6/site-packages (from requests->Mastodon.py)
Requirement already satisfied: idna<2.7,>=2.5 in /anaconda3/lib/python3.6/site-packages (from requests->Mastodon.py)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /anaconda3/lib/python3.6/site-packages (from requests->Mastodon.py)
Requirement already satisfied: certifi>=2017.4.17 in /anaconda3/lib/python3.6/site-packages (from requests->Mastodon.py)
Installing collected packages: Mastodon.py
Successfully installed Mastodon.py-1.1.2
'''
And after that the error persist (though the line changed, now it say it's at line 451)

**Comment by cedricviaccoz** [comment]
Yeah here it is : 
```python
   credentials.checkIfCredentials(APP_NAME)

    cliowireConn = credentials.log_in(APP_NAME, BOT_LOGIN, BOT_PSWD)

    geopulses = Mastodon.search(HASH_MARKER, False)
```

"credentials" is another script where I put all the function to register the app and log the bot.
checkIfCredentials will check if the *_clientcred.secret are already generated, if not it will register the app this way : 
```python
Mastodon.create_app(
     appName,
     api_base_url = DOMAIN_NAME,
     to_file = appName + CLIENT_CRED
    )
```

And log_in has this code :
```
def log_in(appName, userLogin, userPswd):
    mastodon = Mastodon(
        client_id = appName+CLIENT_CRED,
        api_base_url = DOMAIN_NAME
    )

    mastodon.log_in(
        userLogin,
        userPswd,
        to_file = appName+USER_CRED
    )

    # Create actual API instance
    return Mastodon(
        client_id = appName+CLIENT_CRED,
        access_token = appName+USER_CRED,
        api_base_url = DOMAIN_NAME
    )
```

But I'm suspecting that my my pip is somewhat linked to anaconda3, and still installing Mastodon.py using the conda package...

Thank you very much for the assistance !

**Comment by cedricviaccoz** [comment]
Oh wait I'm stupid, I'm calling search on Mastodon, and not the instance I generated (called "cliowireConn"), if I use seach on it, it does work !! 

So sorry for waisting your time !

**Comment by halcy** [comment]
Oh! I see now.

You need to call "search" on the mastodon object, not on the module - try calling it on what gets returned from log_in.
