### ISSUE TITLE
timeline_hashtag should accept and strip a leading hash

### ISSUE THREAD

**Issue by codl** [halcy/Mastodon.py#105]
or at least it should detect it and throw a helpful error

instead what happens is that the hash is passed verbatim to Requests and a request for `/api/v1/timelines/tag/#foobar` is made, which inevitably returns a 404 and throws a confusing "endpoint not found"

**Comment by halcy** [comment]
I wonder if there is any future situation where stripping it might be a problem, but I can't think of any, so probably stripping would be fine.

**Comment by codl** [comment]
hmm i suppose mastodon could start supporting hashtags with more than one hash (it doesn't atm) & then it would be ambiguous whether `timeline_hashtag('#foo')` should get `#foo` or `##foo`

i guess it'd be safer to just throw an error or a warning if the user asks for a hashtag with a leading hash

then if mastodon changes, the error or warning can be removed and the api doesn't have to change
