### ISSUE TITLE
Cannot get Status's 'application' value

### ISSUE THREAD

**Issue by itsumonotakumi** [halcy/Mastodon.py#115]
Hi all,

I tried to get 'application' value of status by Mastodon,py.
But I could get it. My sample is the following code.

> mastodon = Mastodon(client_id=CLIENT_CRED_FILE, access_token=ACCESS_TOKEN_FILE, api_base_u
rl='https://pawoo.net' )
> USERID = (mastodon.search(q='itsumonotakumi@pawoo.net'))['accounts'][0]['id']
> status_list = mstdn.account_statuses(id=USERID)
> print(status_list[0]['application'])

Is there something wrong?

Regards,
Itsumonotakumi

**Comment by halcy** [comment]
Hi and thanks for your report,

other than typoing mastodon to mstdn in the second to last line, your code is correct - however, the "application" field can be "None" (this is the case for everything posted from the web UI right now), so in case of None, just assume web UI in your code.

I'll add this to the documentation to close this issue.

**Comment by itsumonotakumi** [comment]
Hi halcy,

Thank you for your answer. I could understand your comment but could not get 'application' value even if I posted from WEB UI. Please test my code. (Please fix my typo..)

By the way, I always do not use WEB UI, but the application value is None.

**Comment by halcy** [comment]
I've played around a bit, and found that the application field does behave a bit weirdly and differently from how I thought it did:

1) For remote statuses the application is never set. I guess it does not federate?
2) For local statues, it is mostly set (in case of web UI, to an app with name "Web") but sometimes it is None anyways. Probably for legacy appplications from before the application field was a thing?

This doesn't explain your problem, though - you're asking pawoo for statuses and are using a pawoo account. Which works for me:

```
api3 = Mastodon(
    client_id = 'pawoo_client.secret',
    access_token = 'pawoo_halcy_user.secret',
    api_base_url = 'https://pawoo.net'
)
USERID = (api3.search(q='itsumonotakumi@pawoo.net'))['accounts'][0]['id']
status_list = api3.account_statuses(id=USERID)
print(status_list[0]['application'])
```

Results in:
{'website': '', 'name': 'Mastodon Share'}

I have no idea what is going wrong there.

**Comment by itsumonotakumi** [comment]
Thank you for your checking.
I checked it again and understood you were correct.
I could understand this is the specification of Mastodon API.
Therefore I close this case. Thanks!
