### ISSUE TITLE
Confusion between versions in the documentation

### ISSUE THREAD

**Issue by lordminx** [halcy/Mastodon.py#116]
When looking at http://mastodonpy.readthedocs.io/en/latest/ the title still says "Mastodon - Mastodon 1.1.2 documentation", while actually documenting the current (developer?) version, not the 1.1.2 release.

This greatly confused me when looking up the documentation for the API for streaming endpoints, since these changed between [the 1.1.2 release](http://mastodonpy.readthedocs.io/en/1.1.2/#streaming) and the [current developer version](http://mastodonpy.readthedocs.io/en/latest/#streaming).

Secondly (Though that might be more a feature request/philosophical musing.):

When navigating to just http://mastodonpy.readthedocs.io you're automatically redirected to http://mastodonpy.readthedocs.io/en/latest/ . I'm not familiar with the inner workings of readthedocs, but might an automatic redirect to http://mastodonpy.readthedocs.io/en/stable/ not make more sense? When looking up the documentation for a package I want to use, I'd expect the default docs to reflect the version available in PyPI, not the dev version, especially when the dev version changes the API.

**Comment by halcy** [comment]
This has been bothering me also. I'm going to look into it.

**Comment by halcy** [comment]
I've changed two things: http://mastodonpy.readthedocs.io now points to "stable" (latest tagged release) by default, and the title for the latest version is now different. That should make things a lot less confusing.

That said, the next version is coming out in a few hours to days (soon as Mastodon 2.1.0 is out), and I hope to not have any further breaking changes, so if you feel you'll need any of the new stuff added, it's probably safe to develop against current master right now.

**Comment by lordminx** [comment]
Cool, thanks, I probably will. :)
