### ISSUE TITLE
StreamListener should either support listening to >1 stream, or raise when made to listen to more than one stream

### ISSUE THREAD

**Issue by codl** [halcy/Mastodon.py#119]
as of 1.2.1, if a StreamListener listens to two streams at once and an event arrives on both streams at once:

```python
from mastodon import *

class CoolListener(StreamListener):
    # let's pretend this needs to keep track of state across both streams which is why we reuse it
    pass

listener = CoolListener()

api = Mastodon(...)
api.stream_user(listener, async=True)
api.stream_local(listener, async=True)
for _ in range(5):
    api.status_post('hello!', visibility='public') # this will go to both streams
```

there's is a pretty high chance that the events will get interleaved, and both stream threads will crash

**Comment by halcy** [comment]
Hm. Where it breaks is in the calls to handle_line, I think (handle_stream itself does not keep any state). I wonder what a reasonable solution might be.

It'd probably be best to turn handle_line into something like parse_line, getting and returning an event dict, and leave the dispatching to handle_stream, which can then keep the event as a local variable, which should circumvent any problems?
