### ISSUE TITLE
rename "async" function params in preparation for python 3.7

### ISSUE THREAD

**Issue by codl** [halcy/Mastodon.py#120]
https://github.com/halcy/Mastodon.py/blob/c1a6772247a086f6e8b39b4b550a1fb22b67bf83/mastodon/Mastodon.py#L1384-L1389

all the `stream_` methods accept an `async` parameter, however, [`async` is becoming a reserved keyword in Python 3.7](https://bugs.python.org/issue30406)

there is no hurry as the first 3.7 release candidate is planned for late may and final 3.7.0 release sometime in june 😁

**Comment by halcy** [comment]
well that seems like a terrible language keyword decision but also easy to change
