### ISSUE TITLE
tests and docs are not including in pypi archive

### ISSUE THREAD

**Issue by csmall** [halcy/Mastodon.py#126]
If you git clone the repository you get the docs and tests directories but the pypi archive does not have
them.

I guess you could not have tests there are they could be for development, not deployment. I would have thought the documentation was needed though.

Up to you either way, just pointing out they are different.

**Comment by halcy** [comment]
Honestly, I have no idea. Are these things usually included? All the pypi packaging docs I read were very confusing, if there's anything with best practices anywhere, I'm happy to go and fix this up.

**Comment by neelkamath** [comment]
It doesn't matter if they're included or not. But no, the generated documentation needn't be in the Pypi package as the user will either view it using `help(mastodon)` in the REPL or see the website (obviously not by looking at the Python package installed).

**Comment by csmall** [comment]
Just add

```
recursive-include docs *
recursive-include tests *
```

to MANIFEST.in

**Comment by halcy** [comment]
Sure, why not. Done.
