### ISSUE TITLE
Decorator module dependency problem

### ISSUE THREAD

**Issue by MoMaT** [halcy/Mastodon.py#136]
The _decorator_ module prior to version **4.0.0** does not implement the `decorate` function. Distributions like Ubuntu Trusty or Debian Jessie come with decorator **3.4.0** which satisfies the requirements, but leads to a broken package.

To avoid the problem, you could either specify minimum _decorator_ version as 4.0.0 (so that it's upgraded from pypi when needed), or use the old way of creating decorated functions, that is returning: `decorator(wrapper, function)` instead of: `decorate(function, wrapper)`. According to the [documentation](http://decorator.readthedocs.io/en/latest/tests.documentation.html#what-s-new-in-version-4) it does the same job, but is deprecated and available only "for now" (almost 3 years now :) ).

**Comment by halcy** [comment]
Thanks for the report. I think we should be doing the former - I really don't want to be using deprecated functions (sorry, potential debian maintainers).

**Comment by halcy** [comment]
now requiring >=4.0.0
