### ISSUE TITLE
Error using update_credentials to update the avatar

### ISSUE THREAD

**Issue by Lertsenem** [halcy/Mastodon.py#137]
I'm getting 500 errors when trying to upload new avatars, using the documented method.

My code goes as follow:

```
image = requests.get( image_url )
image_extension = image_url.split(".")[-1]
image_64_raw = base64.b64encode( image.content )
image_64 = "data:image/{};base64,{}.format( image_extension, image_64_raw.decode("ascii")
```

mstdn.account_update_credentials( avatar = image_64 )`

(where `mstdn` is a valid Mastodon instance and `image_url` a valid image url, of course).

The result is just:
```
('Mastodon API returned error', 500, 'Internal Server Error', None)
```

I am obviously missing something, but I can't figure what it is... please help ?

**Comment by Lertsenem** [comment]
I just tried with an instance I owned and checked the logs. I am getting those errors when uploading: 

```
 Paperclip::AdapterRegistry::NoHandlerError (No handler found for "data:image/jpg;base64,/9j/4AAQSkZJR[...]
```

So, the image is correctly uploaded, but the format is wrong? That's strange, I'm certain my uploads have worked in the past...

**Comment by codl** [comment]
You're not supposed to build a `data:` url, instead pass the raw image data as `avatar` and the mime type as `avatar_mime_type`

```python
image = requests.get(image_url)
image_extension = image_url.split(".")[-1]
mstdn.account_update_credentials(
    avatar=image.content,
    avatar_mime_type="image/{}".format(image_extension)
)
```

Incidentally I think this should have raised an exception in this case but it doesn't?

https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py#L1233-L1234

**Comment by Lertsenem** [comment]
Thanks, I'll try that!

Anyway, the doc should probably be updated (or maybe I read it wrong?): https://mastodonpy.readthedocs.io/en/stable/#mastodon.Mastodon.account_update_credentials

**Comment by codl** [comment]
ahh my bad, ignore my previous comment, I was looking at stuff that is in master but not yet released. the latest release does expect you to build a `data:` url yourself

**Comment by halcy** [comment]
Yes. This is a recent change. It's not Out There yet because I've been busy but today is the day!

**Comment by halcy** [comment]
(fixed in master)

**Comment by miewliie** [comment]
Hi @halcy @codl, 
I trying to use `account_update_credentials` with `avatar=avatar_url, avatar_mime_type="image/gif"` but received ('Mastodon API returned error', 500, 'Internal Server Error', None) Am I missing something?

**Comment by miewliie** [comment]
> 

Ahh I got it fixed. I used the wrong url for my `avatar_url`
