### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by ProgVal** [halcy/Mastodon.py#14]
Hi,

If my understanding is correct, Mastodon has streaming API(s), but I can't see it in Mastodon.py's doc.
Is it a planned feature?

**Comment by halcy** [comment]
I believe the streaming API is presently internal only / liable to change? Once it's public, sure (though I don't have much time to actually work on this right now...)

**Comment by Gargron** [comment]
Streaming API is public https://github.com/tootsuite/mastodon/blob/master/docs/Using-the-API/Streaming-API.md

**Comment by halcy** [comment]
Oops, completely missed that. I guess I should add support for that at some point, though I think priorities are OAuth > Pagination > Streaming? I don't really have much time right now, in any case. :(

**Comment by wjt** [comment]
I have an extremely WIP patch on https://github.com/wjt/Mastodon.py/tree/streaming, pretty easy to get something roughly working but the devil will be in the details: error handling, rate-limiting (?), …

**Comment by halcy** [comment]
Addressed by #30
