### ISSUE TITLE
feature request: convenience function for replies

### ISSUE THREAD

**Issue by codl** [halcy/Mastodon.py#140]
i find i often have to reimplement a function for replying to a status, mentioning the author or all parties involved. i think it would be a great addition as a convenience function

if this sounds good i can work on implementing it

**Comment by halcy** [comment]
Yeah I've been missing something like that myself. One argument against it I guess is that it's not a proper mastodon endpoint but it's such an extremely common operation that it probably should exist as a function (and it's actually a bit involved, since it needs to also retain visibility and cw).
