### ISSUE TITLE
'pytest-runner' not a setup requirement

### ISSUE THREAD

**Issue by makefu** [halcy/Mastodon.py#141]
currently `pytest-runner` is marked as a setup requirement but actually it is only needed for testing.
For the sake of keeping the dependencies clean it would be great if you could move the dependency to test_deps ( https://github.com/halcy/Mastodon.py/blob/master/setup.py#L3 ).

Cheers!

**Comment by halcy** [comment]
Hm, I wonder why it is like this. Maybe for some weird CI related reason?

I'll move it and see if anything breaks, and if not, I'll close this.

**Comment by makefu** [comment]
fair enough, i patched the line out in my build script to avoid the test dependencies

**Comment by halcy** [comment]
Seems to work just fine with it moved to test-deps. Guess it was just an oversight.

Thanks for the report!
