### ISSUE TITLE
The documentation about status.language cites the wrong standard

### ISSUE THREAD

**Issue by allo-** [halcy/Mastodon.py#142]
The documentation says:
> 'language': # The language of the toot, if specified by the server,
>                 # as ISO 639-2 language code.

I think it is unintuitive to mention only the standard anyway. I had to look it up and [wikipedia says](https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes) that ``ISO 639-2`` are the three-letter language codes. But Mastodon.py (and probably the Mastodon API itself) return two-letter language codes (probably ``ISO 639-1``?).

**Comment by halcy** [comment]
Oops - I think I copied that (maybe typo'd) from the official API docs. Yeah, it should definitely be 639-1, then.

For more easy accessibility, do you think it might be good to literally just link the wikipedia page, or do you know of any other good reference resource / have a better idea how to handle this?

**Comment by allo-** [comment]
I am not sure. I would guess most people know these language abbreviations (at least for the languages which directly concern them) while the name of the standard does not tell them anything before they look it up.
So somebody e.g. listening for hashtags does usually not have the problem, but someone building a full client needs to know the full list of codes.

Wikipedia links the library of congress, which has a similiar table as wikipedia itself here: https://www.loc.gov/standards/iso639-2/php/code_list.php, which may be more representative.

The ISOstandard itself seems to be paywalled, but I think nobody cares about the full standard but only about the abbreviations needed to work with the API.

To keep it simple the documentation in the example dict could be "# as two-letter language code (ISO 639-1)" and "Specify language to override automatic language detection. The parameter accepts all valid ISO 639-2 language codes." can link either wikipedia or the LOC page or some other document with the list.

**Comment by halcy** [comment]
Thank you! That seems like good wording. I'll change it next time I touch the docs!
