### ISSUE TITLE
Providing MIME type to media post raises `Mastodon API returned error`

### ISSUE THREAD

**Issue by errbufferoverfl** [halcy/Mastodon.py#145]
## Expected Behavior
When you create a new media post passing the MIME type:
```python
media = api.media_post(dir_path + "/images/myimage.jpg", mime_type='image/jpeg')
```
it should create a media post using the passed MIME type that can then be attached to a status. When posted it should return as normal.

## Current Behavior
If you specify the MIME type as shown in the example above, and attach the image to a status and post it, the API returns the following exception:

```text
('Mastodon API returned error', 422, 'Unprocessable Entity', 'Validation failed: File content type is invalid, File is invalid')
```

## Possible Solution
I have done some testing and the problem appears on line `1722` in the `media_post` function, because if the MIME type is set, the media file is never opened and passed to the `media_file_description`.

```python
 if mime_type is None and os.path.isfile(media_file):
    mime_type = mimetypes.guess_type(media_file)[0]
    media_file = open(media_file, 'rb')
```

My proposed solution would be something like:

```python
    if mime_type is None and os.path.isfile(media_file):
        mime_type = mimetypes.guess_type(media_file)[0]
        media_file = open(media_file, 'rb')
    elif mime_type and os.path.isfile(media_file):
        media_file = open(media_file, 'rb')
```

## Steps to Reproduce (for bugs)
1. Create media post and specify the correct MIME type: `media = api.media_post(dir_path + "/images/mymedia.jpg", mime_type='image/jpeg') `
2. Attach to a status post and post to Mastodon: `api.status_post(message, media_ids=media, visibility='private', )`

## Your Environment
* Version used: `Mastodon.py==1.3.1` with Python 3.6

**Comment by halcy** [comment]
Fixed.
