### ISSUE TITLE
request: backwards paging (Mastodon 2.6.0+)

### ISSUE THREAD

**Issue by jfmcbrayer** [halcy/Mastodon.py#148]
I'd like to request support for certain Mastodon v2.6.0 features. The most important is backwards paging: 

> ### Support backwards pagination (#8736)

> The new pagination param min_id is the symmetrical opposite of max_id, i.e. it can be used for stepwise pagination from older to newer statuses. The difference to since_id is that since_id will always return the latest statuses, just merely cut off by the provided ID. The new param is supported on all API methods that return statuses.

This is needed for pagination in https://github.com/jfmcbrayer/brutaldon, in particular; right now I only have a link for older statuses, rather than older and newer, because the old Mastodon pagination API didn't work the way users expected it to.

**Comment by halcy** [comment]
Somebody wrote a patch for this but I can't seem to find it now oof

I'll try to get on it

**Comment by jfmcbrayer** [comment]
If you can't find the patch, I actually wouldn't mind writing it. The only thing I'm not sure about is what to do if someone misguidedly sends both min_id and since_id parameters.

**Comment by halcy** [comment]
Fixed in 5340087325242a7a43c97f8218aeb8f2b5b44ef0

**Comment by jfmcbrayer** [comment]
Very nice! Thank you for all the work you've been putting in to Mastodon.py. Will this be in a pypi release soon?

**Comment by halcy** [comment]
Likely tomorrow, if not then next weekend.
