### ISSUE TITLE
On Pleroma user_stream crashes after first pass

### ISSUE THREAD

**Issue by johnchidgey** [halcy/Mastodon.py#154]
Hi! I've been using the Python library for quite some time and recently (three months ago) switched to Pleroma. They 'advertise' they are Mastodon v1 API compliant, however I'm sure that not 100% the case. Either way, I've been unable to run up a project MastodonToTwitter that uses the Python library and I've tracked the problem down (I think) to the handle_stream function in streaming.py
The script loads, negotiates with both Twitter and Mastodon (or Pleroma) and then when it comes time to kick off the thread for monitoring the stream, the line_buffer makes it through the entirety of the of the initial response, chunk/character at a time, then the thread exits completely. I'm not the best at Python and there's a lot of knowledge about this wrapper I don't have.
Also I've run the same breakpoints against a Mastodon instance where it works as intended, and the thread running the handle_stream function never exits, so clearly something is causing the thread to terminate only on Pleroma and I'm struggling to figure out why.
 Not sure if you are able to look into it at some point because I've hit the limit of my knowledge. Thanks in advance for any assistance.

**Comment by halcy** [comment]
hm, unfortunately, without knowing what broke, I really can't

maybe someday I'll test against pleroma, until then, I will be fixing some stuff in the stream handling so maybe that'll also fix this. I will comment here when that's done and maybe you could test again at that time.

**Comment by halcy** [comment]
#155 is fixed in master now so maybe this is also fixed. Please reopen if not (or if you can provide more details / logs of some kind)
