### ISSUE TITLE
Using handle_stream with gzip breaks per-character parsing

### ISSUE THREAD

**Issue by bitkeks** [halcy/Mastodon.py#155]
Hi all,
while developing [my Mastodon-Twitter bot](https://github.com/bitkeks/mastodon-to-twitter) I ran into a parsing problem using the streaming API. At first I'll dump my error case, below you find the details of the bug which might be the cause. The case looks like the following: the received `event` JSON for a status deletion event could not be parsed correctly because the `\n` was not identified.

```
INFO - Own Toot was filtered out due to visibility filter
Chunk: b'e'
Chunk: b'vent: '
Chunk: b'd'
Chunk: b'e'
Chunk: b'l'
Chunk: b'e'
Chunk: b'te\n'
Chunk: b'data: '
Chunk: b'123456'
Chunk: b'\n'

Line: event: delete
data: 123456

Chunk: b'\n'

Line: 

ERROR - Catched MastodonMalformedEventError!
ERROR - ('Missing field', 'data', {'event': 'delete\ndata: 123456'})
```
As the script is using the `StreamListener`, I think I found a bug in the parsing logic which should detect line breaks when receiving chunks of data. The function `def handle_stream(self, response)` does the following:

```python
for chunk in response.iter_content(chunk_size = 1):
    if chunk:   
        if chunk == b'\n':
```
That works if `iter_content` does indeed return one value at a time. But as [the requests docs](https://docs.python-requests.org/en/latest/_modules/requests/models/#Response.iter_content) states, _The chunk size is the number of bytes it should read into memory.  This is not necessarily the length of each item returned as decoding can take place_.

The variable chunk size can be detected by printing each chunk:
```
Chunk: b'\\" rel=\\"'
Chunk: b'me'
Chunk: b' '
Chunk: b'no'
Chunk: b'follow'
Chunk: b' no'
Chunk: b'ope'
Chunk: b'n'
Chunk: b'er'
Chunk: b'\\" '
```
Now, this leads to the question, if the decoding of gzip might break the single character limits, as it is "packed" differently. Printing the `response.headers` reveals that `Content-Encoding: gzip` was indeed used. If we now change https://github.com/halcy/Mastodon.py/blob/8b8626978752baf14347498640b2319db832145e/mastodon/Mastodon.py#L2334 

to 
```python
headers = {"Authorization": "Bearer " + self.access_token, "Accept-Encoding": "none"}
```
gzip is not used and we read each chunk as expected:

```
Chunk: b'e'
Chunk: b'v'
Chunk: b'e'
Chunk: b'n'
Chunk: b't'
Chunk: b':'
Chunk: b' '
Chunk: b'd'
Chunk: b'e'
Chunk: b'l'
Chunk: b'e'
Chunk: b't'
Chunk: b'e'
Chunk: b'\n'
Chunk: b'd'
Chunk: b'a'
Chunk: b't'
Chunk: b'a'
Chunk: b':'
Chunk: b' '
```

This fixes the `MastodonMalformedEventError` caused by undetected `\n`. So, maybe the stream parser needs pre-decoding of gzip? Or the iterator should work differently, reading the bytes of decoded chunks?
Thanks!

**Comment by halcy** [comment]
oof. good catch.

I'll probably just add a second round of iteration, going over each character in "chunk". that would fix this, presumably.

**Comment by bitkeks** [comment]
Hey @halcy, thanks for the fix! I have also made good experiences with using the [response.iter_lines()](https://3.python-requests.org/user/advanced/#streaming-requests) when streaming from the Mastodon API. Maybe this might be a more suitable solution?

Example snippet from my other application:

```python
resp = session.get(url(instance), headers=headers, stream=True, timeout=30)
for line in resp.iter_lines(decode_unicode=False):
    if line.startswith(b"data: "):
        data = json.loads(line[len("data: "):].decode())
        ...
```
