### ISSUE TITLE
Use without authentication

### ISSUE THREAD

**Issue by cerisara** [halcy/Mastodon.py#159]
Hi,

Sorry, but it is not clear for me: how can we use this python API to access the few methods that are described as "do not requiring authentication" ?
The constructor requires auth, and there I've not seen static methods for reading a public status for instance...

Thank you !

**Comment by halcy** [comment]
It... shouldn't?

Mind, "no authentication" does not mean "no credentials whatsoever" - you still need an API key (which create_app can generate for you or which you can generate in the web UI manually). You just don't need to log in as any specific user.

if doing that does not work, then that's a regression, but last I checked it worked just fine (and I think we have tests that test this, too)

**Comment by cerisara** [comment]
OK, I understand, it's a design choice;
But the original API supports this: for instance, you can do, without any account nor key:
curl https://mastodon.social/api/v1/timelines/public?local=1

So the Mastodon.py wrapper does not support this use case.
Of course, we can do it with python requests for instance, but it would have been nice to benefit from the
paging feature that is already implemented in Mastodon.py

**Comment by halcy** [comment]
I did not know that you can do that now tbh

guess I'll have to go look at a bunch of endpoints to see which work how when I next have the energy to actually do maint. Reopening as a reminder.

**Comment by codl** [comment]
All of the endpoints marked in the docs as not needing authentication, do not require app credentials

Aaand also some marked as needing auth, for some reason

As of v2.8.0 they are:

* `GET /api/v1/accounts/:id`
* `GET /api/v1/accounts/:id/statuses`
* `POST /api/v1/apps` (no surprise there)
* `GET /api/v1/custom_emojis`
* `GET /api/v1/instance`
* `GET /api/v1/polls/:id`
* `GET /api/v1/statuses/:id`
* `GET /api/v1/statuses/:id/card`
* `GET /api/v1/statuses/:id/context`

**Comment by halcy** [comment]
Fixed in fb7496c68db5941528d0e32d821b58e255b2cb51

Historical note: The trends endpoint was also usable without auth, but was only ever experimental and does not exist anymore.

**Comment by cerisara** [comment]
Thank you !

**Comment by codl** [comment]
would you say the trends endpoint was only a passing trend
