### ISSUE TITLE
Search no longer works on Mastodon < 2.8.0

### ISSUE THREAD

**Issue by jfmcbrayer** [halcy/Mastodon.py#167]
The required version for mastodon.search() and mastodon.search_v2() were bumped to 2.8.0, probably because 2.8.0 added paging parameters. However, it should still be possible to search without paging on Mastodon < 2.8.0, as it was before.

This is causing https://github.com/jfmcbrayer/brutaldon/issues/63.

**Comment by halcy** [comment]
Oh bother, yeah, it should not be broken. I did change search to use search_v2 by default, but that should still work on older (though not TOO old) versions. Maybe it should select what function to use dynamically based on if v2 is available anyways.

I'll look into it.

**Comment by halcy** [comment]
Fixed in 8675b25dcfc4a0da1e2dbcff07a359a83d32dd4a

**Comment by halcy** [comment]
Unsure why the comments are out of order. Fixed in 8675b25dcfc4a0da1e2dbcff07a359a83d32dd4a

**Comment by jfmcbrayer** [comment]
Thanks for the fast fix; this probably merits a release in order to fix broken clients. (Selfishly, I want this to fix brutaldon).

**Comment by halcy** [comment]
yeah, will absolutely do a release, I just want to also get full 2.8.2 support in and re-run the unit tests. Will likely do all of that after I get home from work, I already got blurhash decoding working yesterday, so expect 1.4.1 in maybe 10 to 12 hours from now.

**Comment by halcy** [comment]
well, might unfortunately not quite make it today, but tomorrow, I'll definitely get this done.
