### ISSUE TITLE
Optional support for self signed certificates

### ISSUE THREAD

**Issue by Oupsman** [halcy/Mastodon.py#168]
Hello,

I'm perfectly aware that self signed certificates are the devil, but in certain cases (private testing instance), it would be ideal to have one. 

So it would be really great if we could use selfsigned certificate with Mastodon.py

**Comment by halcy** [comment]
Mastodon.py uses requests internally, and allows you to specify a custom Session object, so you can already do this:

https://2.python-requests.org/en/master/user/advanced/ (ctrl-f "ssl cert verification").

Should be as easy passing in a session with "verify = False" to Mastodon.pys constructor!

Let me know if that works for you. If so, I'll put it in the docs somewhere.

**Comment by Oupsman** [comment]
Hi, I've been trying to pass a session object for several days now, but my code doesn't seem to work :+1: 
uc_client_id     = get_parameter("client_id",     secrets_filepath)
uc_client_secret = get_parameter("client_secret", secrets_filepath)
uc_access_token = get_parameter("access_token", secrets_filepath)
mastodon_hostname = get_parameter("mastodon_hostname", secrets_filepath)
verify_ssl = get_parameter('verify_ssl', secrets_filepath)

s = requests.Session()
s.verify = verify_ssl

mastodon = Mastodon(
    session = s,
    client_id = uc_client_id,
    client_secret = uc_client_secret,
    access_token = uc_access_token,
    api_base_url = 'https://' + mastodon_hostname,

)

I have the following message : 

oupsman@CHIOT:/mnt/c/Users/benoi/PycharmProjects/untitled$ python3 nsfw-bot.py
Traceback (most recent call last):
  File "nsfw-bot.py", line 274, in <module>
    api_base_url = 'https://' + mastodon_hostname,
TypeError: __init__() got an unexpected keyword argument 'session'

**Comment by halcy** [comment]
Hm, that is a bit weird. Which Version of Mastodon.py are you using?
