### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by halcy** [halcy/Mastodon.py#17]
Mastodon.py should support 2FA for logging in.

**Comment by azillion** [comment]
I think 2FA is supported if they use OAuth.

When the user is redirected to the url, from auth_request_url, they have to login before authorizing, which handles the 2fa. The Tusky android app uses this way to support 2fa without supporting it inline.

**Comment by azillion** [comment]
Confirmed with @Gargron that 2fa is handled by using oauth

**Comment by halcy** [comment]
Alright, closing this, then.
