### ISSUE TITLE
account_statuses and authentication

### ISSUE THREAD

**Issue by bortzmeyer** [halcy/Mastodon.py#178]
The documentation says " Mastodon.account_statuses [...] Does not require authentication." 

It does not fit the description ("Returned toots are from the perspective of the logged-in user, i.e. all statuses visible to the logged-in user (including DMs)") nor my experience (without authentication, I get a 401). 

I suggest the documentation may be wrong.

**Comment by halcy** [comment]
Hm, thanks for the report. I wonder why I wrote that there. I'll check later and adjust the docs. It would make sense if it worked without auth, and maybe at some point it did - did you try with client-auth yet?

In either case, the docs need to be clarified.

**Comment by bortzmeyer** [comment]
> did you try with client-auth yet?

Yes, and it works as expected.

> In either case, the docs need to be clarified.

Either just remove "Does not require authentication" from the docs, or improve the routine so it returns public toots if not authenticated or all toots if authenticated.

**Comment by halcy** [comment]
Hm.

So I just tried, and I can, without being authed at all, retrieve statuses from Mastodon.social, i.e. the following works and returns public posts by @Gargron@mastodon.social:

```
from mastodon import Mastodon
api_noauth = Mastodon()
api_noauth.account_statuses(1)
```

Can you post an example where it'll 401?

**Comment by bortzmeyer** [comment]
```
#!/usr/bin/env python3

from mastodon import Mastodon

import sys

ME = 369

Mastodon.create_app(
     'testonlyforfun',
     api_base_url = 'https://mastodon.gougere.fr/',
     to_file = 'test_clientcred.secret'
)

mastodon = Mastodon(
    client_id = 'test_clientcred.secret',
    api_base_url = 'https://mastodon.gougere.fr/'
)

toots = mastodon.account_statuses(ME)
for t in toots:
    print(t['created_at'], t['content'])
```

And running it:

```
%  python3 tmp.py
Traceback (most recent call last):
  File "tmp.py", line 20, in <module>
    toots = mastodon.account_statuses(ME)
  File "<decorator-gen-18>", line 2, in account_statuses
  File "/home/stephane/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 57, in wrapper
    return function(self, *args, **kwargs)
  File "/home/stephane/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 637, in account_statuses
    return self.__api_request('GET', url, params)
  File "/home/stephane/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 1613, in __api_request
    error_msg)
mastodon.Mastodon.MastodonUnauthorizedError: ('Mastodon API returned error', 401, 'Unauthorized', 'Le jeton d’accès n’est pas valide')
```

The credentials file was created:

```
% ls -alt test_clientcred.secret 
-rw-r--r-- 1 stephane stephane 130 Jun 20 17:22 test_clientcred.secret
```

**Comment by halcy** [comment]
Hm!

I think this behaviour changed somewhere around 2.7, then (gougere.fr is at 2.6). Will try to find out when exactly and document accordingly.
