### ISSUE TITLE
list_accounts always returns at maximum 40 accounts

### ISSUE THREAD

**Issue by ashwinvis** [halcy/Mastodon.py#179]
I use `mastodon-archive`, in this example, but the method is implemented here. Hence, the issue is opened here.

```python
In [1]: from util import args

In [2]: args??
Init signature: args() -> None
Source:
class args:
    """Mimic args for mastodon-archive CLI"""

    user = f"{username}@{domain}"
    pace = False
    skip_favourites = False
    with_mentions = True
    with_followers = True
    with_following = True
File:           ~/Backup/Nextcloud/AppData/mastodon/util.py
Type:           type
Subclasses:

In [3]: from mastodon_archive.core import read

In [4]: mastodon = read(args)

In [5]: mastodon.lists()
Out[5]:
[{'id': 10, 'title': 'News'},
 {'id': 17, 'title': 'High'},
 {'id': 18, 'title': 'Mid'},
 {'id': 20, 'title': 'Low'}]

In [6]: len(mastodon.list_accounts(20, limit=0))
Out[6]: 40
```
The docs say
>  Get the accounts that are on the given list. A `limit` of 0 can
>  be specified to get all accounts without pagination.

but I get just 40. I have manually counted this list, and contains over 100 accounts.

**Comment by ashwinvis** [comment]
Versions:
```
mastodon-archive==1.2.0
Mastodon.py==1.4.5
```

**Comment by halcy** [comment]
guess that changed in some version and I did not update the docs. Will fix in docs for next release, ty.

**Comment by ashwinvis** [comment]
So if it is just a docs issue, how can I get the full list?

**Comment by halcy** [comment]
You can use the pagination API:

`
first_accounts = mastodon.list_accounts(20, limit=0)
all_accounts = mastodon.fetch_remaining(first_accounts)
`

**Comment by halcy** [comment]
fixed by removing that sentence.
