### ISSUE TITLE
Dismiss Notification API

### ISSUE THREAD

**Issue by kensanata** [halcy/Mastodon.py#182]
As mentioned elsewhere (https://github.com/glitch-soc/mastodon/issues/1188), I'm running into an error when trying to dismiss a single notification using *Mastodon.py*. It uses a POST request to `/api/v1/notifications/dismiss` but the answer I was given on glitch-soc says that this is wrong:

> It's supposed to be `/api/v1/notifications/${id}/dismiss`, it seems like `/api/v1/notifications/dismiss?id=…` was supported but deprecated until early July

The official documentation supports *Mastodon.py*'s implementation. I'm unsure of what to say.

**Comment by halcy** [comment]
glitchsoc is probably right and the official docs haven’t been updated, and I guess there is no unit test for this.

**Comment by kensanata** [comment]
OK, I'll create a Mastodon issue for it. :)

**Comment by halcy** [comment]
I will also fix it here soon as I can. Any idea in which version it was changed?

**Comment by kensanata** [comment]
I have no idea. The [documentation of the API call](https://source.joinmastodon.org/mastodon/docs/blob/master/content/en/api/rest/notifications.md#post-apiv1notificationsiddismiss) was changed [4 weeks ago](https://source.joinmastodon.org/mastodon/docs/commit/887ae4dbb74ff4e57e216b6d08de62070f871b65).

**Comment by halcy** [comment]
So, I think the plan here is:

1) Find out when it was removed, or at least find a version where the new API is definitely available
2) Add a switch that makes Mastodon.py use the new API for all versions > that version (like we do with search)
3) Freeze the old dismiss notification test case (if we had one - unsure), create a new one for the new API

to be done for the next release (supporting 3.0)

**Comment by halcy** [comment]
partially done, what's missing:
* verify that the new api does in fact return the notification dict
* adjust test and update docs accordingly if so, remove return if not

**Comment by halcy** [comment]
it does not, removed return, new test exists and passes -> done
