### ISSUE TITLE
Function to get your own user_id

### ISSUE THREAD

**Issue by allo-** [halcy/Mastodon.py#184]
Functions like ``account_followers`` require a user id, even when you want to lookup the followers of the logged in account.
There seems to be no easy way to get your own id in Mastodon.py, so you need to find it using some workaround like reading the user dict from a toot of this account.

Can a `.account_info()`` function be added, that returns the user dict for the currently active account?

**Comment by halcy** [comment]
that function is account_verify_credentials. I am not fond of the name either. Docs could specifically point this out, I guess?

**Comment by allo-** [comment]
Indeed, that's what I was looking for.

What about adding it to the examples at the top of the docs? Quite a few functions need your own user id to work, so it might be a good idea to show a small example how it is used.

Maybe a two line example "read your follower list" could be added, that shows getting your account info and then using the id to fetch your follower list.

**Comment by halcy** [comment]
I'm considering just making the docs more clear, and possibly adding a function alias for this one thing like we have for reply, which needs updating anyways (oops), probably called "me()" or something.
