### ISSUE TITLE
Make blurhash a core dependency

### ISSUE THREAD

**Issue by halcy** [halcy/Mastodon.py#198]
Blurhash will change back to a more permissive license with the next release (I maintain it and it's completely my code, so I can just, well, do that) and is light on requirements, so there will be little reason to not have it be in the default requirements anymore.

Package maintainers please scream if there actually is a good reason for it not to be in there.

**Comment by craigmaloney** [comment]
For Tootstream we're not using it, but it doesn't seem to add any external dependencies so I'm not finding an issue with incorporating it.

**Comment by halcy** [comment]
yeah, the previous issue is I'd been using it to test licensing something with a less permissive license (for packagers, this obviously is an issue!), and having evaluated doing that, I'll probably go back to plain MIT.

**Comment by halcy** [comment]
done
