### ISSUE TITLE
Toots with hyperlinks (sending HTML?)

### ISSUE THREAD

**Issue by bortzmeyer** [halcy/Mastodon.py#205]
I would like to send toots which include hyperlinks (such as https://botsin.space/@bgp/103079733205573443 ) Apparently, I cannot send raw HTML, it is always escaped. I'm not sure it is the fault of Mastodon.py or of Mastodon itself.

(My main goal is sending hyperlinks. So, a Markdown or Markdown-like format to create toots with hyperlinks would be fine as well. I don't specifically request HTML.)

**Comment by halcy** [comment]
Hm. mainline Mastodon definitely does not allow any formatted text or hyperlinks, so if the other side is a stock Mastodon server you are out of luck. I do know some Mastodon forks, and Pleroma (I think?) and possibly Misskey do allow more than just plain text. I wonder if it "just works" as is (you just send html and that's that) or whether you have to do more than that (like set a "is html" type parameter). If you have to do more than that, I think we should support it.

**Comment by halcy** [comment]
... turns out mastodon.py already supports this. did I implement this while high and forget??

anyways just set feature_set = "pleroma" in the constructor and then set the content_type to text/html or text/markdown or whatever on status_post / status_reply.
