### ISSUE TITLE
[FR] allow to get mentions only when calling Mastodon.notifications() method

### ISSUE THREAD

**Issue by adbenitez** [halcy/Mastodon.py#206]
I need to get only mentions notifications, the same behavior that has the web client which has a tab "all" and "mentions" in the notifications timeline, 
this could be  done adding a parameter to `Mastodon.notifications`  something like `mentions_only=False` that when set to `True` causes the request to be `/api/v1/notifications?exclude_types[]=follow&exclude_types[]=favourite&exclude_types[]=reblog&exclude_types[]=poll`

Thanks for your work, really nice package :+1:

**Comment by halcy** [comment]
Huh, interesting, didn't notice that that's a thing even though it's probably existed for a long time. Will support with next release.

**Comment by halcy** [comment]
Fixed

**Comment by imariasantos** [comment]
Hi !

The `mentions_only` parameter doesn't seem to be used in [`Mastodon.notifications`](https://github.com/halcy/Mastodon.py/blob/e9d2c3d53f7b1d371e5dc5bf47e5fe335b698c85/mastodon/Mastodon.py#L968)

(I love this package, great work)

**Comment by halcy** [comment]
:| oops, yeah, i see. Sorry, I only did one half of that fix.

If you or somebody would like to add it, I'll merge PR and push a minor release, don't have the capacity to actually do it myself right now.

**Comment by arittner** [comment]
@MicroCheapFx, thank you for your contribution
