### ISSUE TITLE
Local timeline omits toots with mentions

### ISSUE THREAD

**Issue by enkiv2** [halcy/Mastodon.py#21]
Context: https://github.com/enkiv2/mastodonVoyeur/blob/master/MastoVoyeur.py

I request the local timeline from a mastodon instance and loop through toots; I have discovered that the array I get contains no toots with mentions, even when it contains toots from the same user both newer and older that have to mentions. This is not limited to mentions of remote users.

**Comment by halcy** [comment]
This is consistent with documentation as well as how mastodon web behaves, is it not? All non-user TLs omit mentions.

**Comment by enkiv2** [comment]
I didn't see anything in the documentation that suggests dropping all toots
with mentions; it looks like this behavior is indeed in line with how the
local timeline works in web (though not the user timeline).

Is there a way to get the toots that have been filtered out? Or, is this
not supported at all by the API?

**Comment by halcy** [comment]
I don't think there is any way to get a free of all toots by every local user at once including replies in the API. Maybe the documentation could be updated to reflect this.

**Comment by halcy** [comment]
Fixed by documentation update.
