### ISSUE TITLE
unable to access an mastodon instance with error code 403 (Access denied | mstdn.jp used Cloudflare to restrict access)

### ISSUE THREAD

**Issue by KodaiWaki** [halcy/Mastodon.py#213]
While trying to access a mastodon instance: mstdn.jp, the access was rejected with the following error
`
Access denied | mstdn.jp used Cloudflare to restrict access
`
Looks the instance requires 
‘User-agent’
in the header of "requests" modle.
E.g. something like the following modification in Mastodon.py 
`response = requests.post(api_base_url + '/api/v1/apps', data=request_data, headers = {'User-agent': 'toot/<version>'} , timeout=request_timeout)` in the create_app() method resolved the problem in my local environment.

Could this be a generic problem? 
If yes, does it make sense to add ‘User-agent’ in each _requests_ call in this module to fix the issue?

**Comment by halcy** [comment]
Interesting. Yeah, that's a good idea, and probably best to send one anyways. I'll change it next update, not sure if I have time to do it this weekend.

**Comment by KodaiWaki** [comment]
Thank you very much for the reaction! It's great to hear that and I appreciate your support.
 I will be looking forward to the update.

**Comment by codl** [comment]
I've been setting `User-Agent` by passing a requests session to the constructor, ie:

```python
import requests
from mastodon import Mastodon

sess = requests.Session()
sess.headers.update({"User-Agent": "my cool app/v0"})
client = Mastodon(..., session=sess)

client.status_post(":)")
```

it's probably worth it to add a default UA string to the session if no session was passed

**Comment by arittner** [comment]
Hello @KodaiWaki, @theoria, @codl 

A functionality to set a `User-Agent` header was implemented. Because I cannot check it with Cloudflare, please check out the code and install Mastodon.py locally (pip install -e /path/to/mastodon-py-download-folder) and check it in your environment. 

Please pass a user agent string to the initializer parameter `user_agent` or write a user agent string into the fourth line of your application secret file (filename passed by `client_id` parameter).

Thank you!

**Comment by KodaiWaki** [comment]
@arittner Thank you for the update! We'll have a look:-)

**Comment by KodaiWaki** [comment]
Hello @arittner ,
I've had a look at the change and tried it out.
It seems, for some instances the user agent is required already for the call of the method:
`Mastodon.create_app()`
Shall we maybe add a default agent like headers={'User-agent': 'some agent'} here ([Mastodon.py#L286](https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py#L286)) as well?
