### ISSUE TITLE
Being able to delete some user's status as admin

### ISSUE THREAD

**Issue by MicroCheapFx** [halcy/Mastodon.py#214]
I have moderation problems with hords of bots and want to be able to batch delete toots as I suspend accounts on reports.

There is actually not such an option.
status_delete() returns a 404.
admin_status_delete(id) or admin_account_moderate(delete_statuses=True) would be great !

**Comment by halcy** [comment]
Hey, while I agree that this would be useful, this library just implements the server side API calls that mastodon has, so you'd have to feature-request it over there -> https://github.com/tootsuite/mastodon

That said, if you use the API to suspend an account, all the associated statuses should get deleted automatically, so for your specific use case everything should already work as you need it to.

As there's nothing I can do here (until Mastodon has an API call that does this), I will close this issue for now.

**Comment by MicroCheapFx** [comment]
Thank you for the quick answer.

Actually, when I suspend an account, it does not delete associated statuses. I have to do it manually.
I opened [an issue about it](https://github.com/tootsuite/mastodon/issues/13588)

This said, I had a further look at how this manual deleting works and found an undocumented API.

`/admin/accounts/{account_id}/statuses`

with the following parameters:

```
{
    "utf8":"✓",
    "authenticity_token":"mysupersecrettoken",
    "page":"",
    "media":"",
    "batch_checkbox_all":"on",
    "delete":"",
    "form_status_batch[status_ids][]":"{status_id}"
}
```
Note that the last parameter key is **litterally** `"form_status_batch[status_ids][]"` and its associated value is an integer.

**Comment by halcy** [comment]
Hm, interesting. I'll have a look at it.

The undocumented admin APIs are generally not super stable, but maybe we can just put this one in there and document that it is, well, undocumented and possibly not stable.

**Comment by MicroCheapFx** [comment]
I may close this issue and let you choose when to re open it if needed.
Thank you for taking time !
