### ISSUE TITLE
Missing revoke method

### ISSUE THREAD

**Issue by fluffy-critter** [halcy/Mastodon.py#217]
The OAuth API provides a `revoke` endpoint which is necessary to allow the application to log itself out of the user's account. Currently there does not seem to be any means of doing this from mastodon.py.

**Comment by halcy** [comment]
it is incredibly funny to me that this library has gone over three years without anybody including me noticing that there is absolutely no way to log off

as per note in README, not currently going to fix it, but if anyone wants to, should be fairly low hanging fruit, and I certainly have the time to do a quick merge + push a release

**Comment by fluffy-critter** [comment]
Yeah, for now I'm just sending the respective oauth command from my end and adding that to the library should be pretty simple. I'll probably take care of that myself at some point.

Another thing I had to do on my end was add the `state` parameter to the login link too (also necessary for web-based login flows). I'll probably pick that up as well, since that's literally a one-line fix.

**Comment by fluffy-critter** [comment]
for reference, https://github.com/PlaidWeb/Authl/blob/4ede367799124a85e9972adecdc5f28a211658ad/authl/handlers/fediverse.py#L181 for the state parameter and https://github.com/PlaidWeb/Authl/blob/4ede367799124a85e9972adecdc5f28a211658ad/authl/handlers/fediverse.py#L229 for the revoke verb

**Comment by halcy** [comment]
Fixed in 24c686f6b274e04082b13f159ea10d995c2ca281 - @fluffy-critter , if you could have a look at this (revoke and state parameter) and let me know if it matches what you need or if there are any issues, that'd be great (I don't really know oauth very well - I did test the revoke method, and it works, but have not tested the state passing).

**Comment by fluffy-critter** [comment]
Gosh, it's been a while since I've thought about this stuff! API-wise it looks fine and I'll trust your testing that it works as intended. :)
