### ISSUE TITLE
Modularize and seperate logic

### ISSUE THREAD

**Issue by azillion** [halcy/Mastodon.py#23]
Modularizing the API to allow for separation of logic.

Just to make the API easier to extend and build off of.

Thoughts?

**Comment by halcy** [comment]
I'm not sure what a good way to split the API up would be. All the constituent parts are rather small, so for now, I think one file makes a lot of sense...

**Comment by azillion** [comment]
It's not a pressing issue at the moment anyway. Maybe something to return to in the future if needed.
