### ISSUE TITLE
Specified client ID directly but did no supply secret

### ISSUE THREAD

**Issue by codinghedgehog-python** [halcy/Mastodon.py#231]
I'm trying to get my bot to connect to my account.
From the docs I've followed:

```
mastodon = Mastodon(
    client_id = 'pytooter_clientcred.secret',
    api_base_url = 'https://mastodon.social'
)
```
so I did:

```
mastodon = Mastodon(
    client_id = 'pytooter_clientcred.tzKlkCLA9bg0k_E2rpFMLZzCJ8',
    api_base_url = 'https://mastodon.social'
)
```
and also tried:
```
mastodon = Mastodon(
    client_id = 'tzKlkCLA9bg0k_E2rpFMLZzCJ8',
    api_base_url = 'https://mastodon.social'
)
```
The secret string isn't complete so don't worry about security here. I'm getting exception `Specified client ID directly, but did not supply secret.` . Clearly I'm supplying it in both cases so why is it complaining ?

**Comment by halcy** [comment]
Hey,

if you want to specify client id and secret directly, here's what you should do:

```
mastodon = Mastodon(
    client_id = 'your client id here',
    client_secret = 'your client secret here',
    api_base_url = 'https://mastodon.social'
)
```

i.e. specify them as separate parameters. Maybe the documentation could be clearer about this.

Later when you've logged in, all you need is the access token and base url.

**Comment by codinghedgehog-python** [comment]
Thank you for replying.

my full script looks as follows (again don't mind the secret strings, they're not real):

```
from mastodon import Mastodon

mastodon = Mastodon(client_id='ejefsofjesfhughiehf', client_secret='ieureorwinfbgkg', api_base_url='https://mastodon.social')
mastodon.log_in('disciple_Mark', 'mypasswordhere',
to_file='fjeislfjiesfslfhbsekfesif', redirect_uri='urn:xxx:xxx:oob')

mastodon = Mastodon(access_token='iejflsfjesifjsghgee', api_base_url='https://mastodon.social')
mastodon.toot('testing tooting ...')
```
error output:

`Invalid username, password, or redirect_uris. ('Mastodon API returned error', 400, 'Bad Request', 'invalid grant')`

Credentials are correct. What does it mean "Invalid grant" ?

**Comment by halcy** [comment]
"invalid grant" is the message from the Mastodon server, and I think in this case it's due to an invalid URI - it either needs to be a valid URI and the exact one registered for the app if you're going for an oauth flow, but since you're not, it has to be "urn:ietf:wg:oauth:2.0:oob". That's also the default, so just remove the parameter, and it should work.

**Comment by codinghedgehog-python** [comment]
I've been using the default `urn:ietf:wg:oauth:2.0:oob`. With or without it keeps pushing back with the same error.
I'll investigate on this. From the looks of it it should work but it doesn't in my case.
Thanks for your support.

**Comment by halcy** [comment]
Hm, weird. Assuming client id and secret are correct and for the correct server, it _should_ work. I hope this isn't a new masto version breaking things, I'm behind on maintenance. If you find out what the issue was, please do let me know

**Comment by arittner** [comment]
Hello @codinghedgehog-python 

Is this issue still valid? Or was it a configuration issue?

**Comment by halcy** [comment]
Closing as stale, guessing they solved their issue. Feel free to reopen if needed.
