### ISSUE TITLE
Proposal to remove Python 2 support and switch dependencies and tests to Python 3.9 and 3.10

### ISSUE THREAD

**Issue by arittner** [halcy/Mastodon.py#236]
For better maintenance, the support for Python 2 should be removed. 

The sunset of Python 2 is already two and a half years ago, and we could remove some libraries (six) and make the code a bit clearer. In addition, it would be useful to add the *tox* environments 3.9 and 3.10 and remove at least 3.6.

**Comment by halcy** [comment]
Well, we're not officially supporting 2 anymore. I think we should attempt to support at least python3 versions as long as possible, and try to not break 2.7 compat anywhere on purpose (just, if it breaks, it breaks).
