### ISSUE TITLE
gotosocial: search() fails due to version check for v1 vs v2.

### ISSUE THREAD

**Issue by fwaggle** [halcy/Mastodon.py#249]
```
  File "/.../mastodon/Mastodon.py", line 467, in verify_minimum_version
    if major > self.mastodon_major:
AttributeError: 'Mastodon' object has no attribute 'mastodon_major'
```

This is because for gotosocial the class doesn't fill out these attributes. There's probably going to be other things that broke but I won't have time to test them all. :(

**Comment by halcy** [comment]
Not setting a default version was probably a mistake. I'll have a look at it tomorrow.

As an aside: You seem to have a lot of experience with gotosocial.

Do you know if it's easy to set up a test instance to try things? Probably can't run most tests against it, but still. And do you know if it implements any APIs that masto mainline does not? We do have a currently not very utilized concept of feature sets for that kind of thing.

**Comment by fwaggle** [comment]
I've actually only started using it last week! But I like it a lot.

It was pretty easy to get going with, there's a docker image I used at first (building from source now as I hope to use it to learn Go): superseriousbusiness/gotosocial

If you only care about testing with it, you can run it from an sqlite database (I'm not sure how well that scales, probably fine for a small instance even). I'm not 100% sure what happens if you create a test instance on a domain, interact with the fediverse, then trash that test instance and make another on the same domain - there are openssl keys for signed web requests that are created and attached to your domain for instance. But if you set it up on a throwaway subdomain just to shoot mastodon requests at it, it's definitely easy enough to get going!

I don't *think* there are any endpoints it implements that Mastodon doesn't yet. They do also have a project to track compatibility with mastodon clients, so some issues might get fixed on their side too.
