### ISSUE TITLE
edited_at is not Python datetime objects

### ISSUE THREAD

**Issue by SouthFox-D** [halcy/Mastodon.py#251]
![image](https://user-images.githubusercontent.com/58982705/200350086-8a70f4d3-d727-4d60-91b6-721b4c7a34f5.png)

**Comment by halcy** [comment]
Yep, that’s because it‘s a new date field. Easy fix, will do it tomorrow, ty for the report

**Comment by halcy** [comment]
tomorrow (valve time). It's fixed in master now.
