### ISSUE TITLE
New release for `instance_health` changes?

### ISSUE THREAD

**Issue by woodruffw** [halcy/Mastodon.py#258]
First of all, thanks for these bindings! I'm looking forward to using them!

It looks like newer Mastodon versions respond to `/health` requests with `OK`, rather than `success`. 

You added a check for that in https://github.com/halcy/Mastodon.py/commit/3277ca777821e76955fb26d80788939a311db9db, but it isn't made its way into a release yet. Would it be possible to get a quick bugfix release that includes that change, so that `Mastodon.py` users can use `instance_health` to check the health of newer servers?

**Comment by halcy** [comment]
Sure, I can push a quick maint release. I somewhat feel for the people maintaning the package for Debian or such, but, oh well.

**Comment by halcy** [comment]
Jsut did, 1.6.1 on pypi now matches what is currently in master.

**Comment by woodruffw** [comment]
Thanks a ton!
