### ISSUE TITLE
Recommendation: add GH topics

### ISSUE THREAD

**Issue by andypiper** [halcy/Mastodon.py#261]
Small suggestion to add some topics to the repository to aid discoverability.

Right now, this repo does not show up in [a search like this](https://github.com/search?q=topic%3Amastodon+language%3APython&type=repositories&s=updated&o=desc&p=2&l=Python)

**Comment by halcy** [comment]
Huh, I really haven’t kept up with github features. I‘ll figure out how to set that up when I have some time and am at an actual computer, thanks.
