### ISSUE TITLE
Mastodon version is set to 1.0.0 when LIMITED_FEDERATION_MODE is activated

### ISSUE THREAD

**Issue by ulysseus-eu** [halcy/Mastodon.py#264]
Hello,

thanks very much for this library that has proven to be very useful.
For community isolation reasons, we have activated LIMITED_FEDERATION_MODE on our mastodon instance.
Because of that, a certain number of API calls need to be authenticated and especially the one used by retrieve_mastodon_version.
This API becomes available as soon as log_in function is called.
Consequently, the version check logic should be moved to the log_in function after the bearer has been retrieved.

cheers !

**Comment by halcy** [comment]
Really enjoying all these recent bug reports from the added activity. This is a blind spot I'd never have found.

ty for report, will be fixed in next version.

**Comment by halcy** [comment]
resolved in master
