### ISSUE TITLE
__unpack_id: TypeError

### ISSUE THREAD

**Issue by pfitzer** [halcy/Mastodon.py#265]
Python 3.9.7

```
 if dateconv and isinstance(id, datetime):
    TypeError: isinstance() arg 2 must be a type or tuple of types
```

should be 

```python
...
        if dateconv and isinstance(id, datetime.datetime):
            id = (int(id) << 16) * 1000
...
```

**Comment by halcy** [comment]
Was fixed (and another bug with the same piece of code and adding tests so that this doesn't happen again) in 1.6.2 (haven't tagged it, did that late yesterday, but it is on pypi).
