### ISSUE TITLE
Do not send all local arguments as params on account_follow

### ISSUE THREAD

**Issue by aveao** [halcy/Mastodon.py#267]
The following line results in sending the account id in formdata in follow requests:

https://github.com/halcy/Mastodon.py/blob/98760f650bcaafedead3f0b6e2b0c594ab857338/mastodon/Mastodon.py#L2244

While mastodon may be okay with this, this results in a HTTP 400 from pleroma:

```
  File "/usr/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ave/.local/lib/python3.10/site-packages/mastodon/Mastodon.py", line 111, in wrapper
    return function(self, *args, **kwargs)
  File "/home/ave/.local/lib/python3.10/site-packages/mastodon/Mastodon.py", line 2247, in account_follow
    return self.__api_request('POST', url, params)
  File "/home/ave/.local/lib/python3.10/site-packages/mastodon/Mastodon.py", line 3704, in __api_request
    raise ex_type('Mastodon API returned error', response_object.status_code, response_object.reason, error_msg)
mastodon.Mastodon.MastodonAPIError: ('Mastodon API returned error', 400, 'Bad Request', None)
 ~/Projects/workbench/c6-fedi  python3 c6fedi.py                                              
```

This is also not compliant with the mastodon API:

![image](https://user-images.githubusercontent.com/6755762/202886681-7a2e607c-1659-47b7-b128-92aa6cb22ac4.png)

ps. if you're testing this you may face another issue relating to expecting booleans and getting strings, this is a pleroma bug and I have an issue and MR out: https://git.pleroma.social/pleroma/pleroma/-/issues/2999

**Comment by halcy** [comment]
I don't really have any way to "properly" test against pleroma (well, I could, but to be honest, testing against masto is a pain already), though I might make an account on some akkoma instance to try a few things eventually

in that sense: thank you for the report, will address with next release

**Comment by halcy** [comment]
Fixed in master, will push update to pip soon, but probably not today
