### ISSUE TITLE
exclude unreviewed ignored

### ISSUE THREAD

**Issue by marianodominguez** [halcy/Mastodon.py#272]
I tried 1.5 and 1.63
`
result=api.search("#mytag", resolve=True, result_type="statuses",exclude_unreviewed=False, min_id=since_id)`

I can see the flag is set as 1
```

INFO:root:Retrieving mentions
DEBUG:urllib3.connectionpool:https://mastodon.cloud:443 "GET /api/v2/search?exclude_unreviewed=1&min_id=109379489588265400&resolve=1&q=%23zxspectrumbot&type=statuses HTTP/1.1" 200 None
```

**Comment by halcy** [comment]
oops - search currently does not pass exclude_unreviewed through to the actual search function. It's an easy fix, I'll add it next release. As a workaround, you can use search_v2 directly for now.

**Comment by halcy** [comment]
Fixed in master
