### ISSUE TITLE
Support pathlib

### ISSUE THREAD

**Issue by reagle** [halcy/Mastodon.py#275]
I just stubbed my toe on this, and it's not a big deal, but it could be nice if "file names" (really paths) supported pathlib directly.

```
media = octodon.media_post(str(photo_path), description=photo_desc)
```

**Comment by halcy** [comment]
ah, that sounds like a good idea, yeah. somewhat complicated by the fact that these functions also needs to take media data directly (so can't just str() it) but it should just be a matter of one more instanceof, I think?

**Comment by reagle** [comment]
I imagine so. Since it is a polymorphic argument and you’re already testing whether it’s a string or bytes, testing if it’s a Path instance shouldn’t be too much more trouble.

**Comment by halcy** [comment]
Haven't added a test yet, but this should now work in master version.
