### ISSUE TITLE
Suggestion: modernise to use pyproject.toml 

### ISSUE THREAD

**Issue by andypiper** [halcy/Mastodon.py#276]
Per PEP 621 the more modern method to specify project metadata with setup tools.

Useful references:
- https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
- http://ivory.idyll.org/blog/2021-transition-to-pyproject.toml-example.html

Optional enhancement - maybe something for the future roadmap more than a required “fix” 🙂

**Comment by halcy** [comment]
Sounds like a good idea, but yeah, going to put this off until we're caught up with 4.x!

**Comment by sneakers-the-rat** [comment]
i'd be willing to draft a PR for this, looks pretty simple :)

**Comment by halcy** [comment]
Anyone who wants to feel free to have a go at this, unless the python packaging people have since deprecated it, again - personally, I just don't care too much

**Comment by codl** [comment]
I'm giving this a shot

hey @halcy is there a reason why blurhash is required regardless of whether the [blurhash] extra is selected?

**Comment by yuval-harpaz** [comment]
I got [this issue](https://stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout) when pip installing the module. For me the error said `error: Multiple top-level packages discovered in a flat-layout: ['srcgen', 'mastodon'].` The solution is supposed to be adding this to toml. 
```
[tool.setuptools]
py-modules = []
```

**Comment by halcy** [comment]
Yeah, pardon the dust - master is currently not in an installable state. I will fix it later today.

**Comment by yuval-harpaz** [comment]
Thanks, I see. Please advise -  I am trying to install in a GitHub workflow, so installing via pip directly from git would fail. Can I do this from another branch, or from a previous commit/tag? I guess I can clone the repo, remove the folder and install it locally every time but it seems messier, and may fail once you change the dir tree.
Thanks again

**Comment by halcy** [comment]
ah, huh.

I will fix it in ~30min, sorry about the breakage, then. It‘d probably be better to point the workflow (not really familiar with how those work) at something other than master, though - master will definitely be not stable in this repo at all times.

**Comment by halcy** [comment]
If you can point it at https://github.com/halcy/Mastodon.py/tree/1.8.1 maybe that would solve your issue? If the goal is to always point at latest stable... I‘m not sure how to do that

**Comment by yuval-harpaz** [comment]
well, with workflows you run a yml, eventually there should be a pip install line, normally referring to a requirements.txt but installing one module from GitHub is not a problem ([here](https://github.com/yuval-harpaz/astro/blob/main/.github/workflows/manual_toot.yml) is where I try to toot). 
In any case,  running `pip install git+https://github.com/halcy/Mastodon.py.git@1.8.1` solved the issue, thanks a lot!

**Comment by astrojuanlu** [comment]
Given that #339 was merged, I guess this can be closed?

**Comment by halcy** [comment]
yes
