### ISSUE TITLE
Connection impossible with Python 3.8

### ISSUE THREAD

**Issue by baeuchle** [halcy/Mastodon.py#277]
I'm running a bot via this package under Ubuntu 20.04 (python 3.8) and Ubuntu 22.04 (python 3.10).

In both cases, I initially tried with version 1.5.1, and have upgraded the distributed package to the current version 1.7.0. I use the same credentials in both cases.

I execute the following code:
````
(... prepare cred = {'access_token': '...', 'api_base_url': 'https://botsin.space' }
import mastodon
m = mastodon.Mastodon(**cred)
m.instance()
````

On Python 3.10, I get the expected instance dict; on Python 3.8, an exception is thrown:
````>>> m.instance()
0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ds100/.local/lib/python3.8/site-packages/mastodon/Mastodon.py", line 112, in wrapper
    raise MastodonVersionError(
mastodon.Mastodon.MastodonVersionError: Version check failed (Need version 1.1.0)
````

I run the bot on other instances, as well, namely zug.network and bahn.social; they work without a problem, it's only botsin.space that plays up.

**Comment by baeuchle** [comment]
Well I started with 1.5.1 and only updated to 1.7.0 prior to writing this issue to check whether it's not a trivial 'use the current version, stupid!' case. So, yes: both 1.5.1 and 1.7.0.

**Comment by baeuchle** [comment]
Oh wait it seems to be a different problem: Calling https://botsin.space/api/v1/instance, I receive a 403 Forbidden status from the Ubuntu 20.04 machine, but the expected JSON from 22.04. This would indicate that it's not about the versions after all. Sorry for bothering.

**Comment by halcy** [comment]
Hm, that's Weird. I wonder why that would happen. Please let me know if you find out why, I'm kind of curious.

Also, I think in trying to triage this I found a different bug, which is that version checks seem to have broken for unauthed API calls, and somehow no test caught this, so that's bad.

**Comment by halcy** [comment]
Ah, nevermind, that was just me forgetting to pass an api base url. Think I need to revamp that and remove mastosoc as default, since it's not going to be what most users want anyways and just causes error potential.
