### ISSUE TITLE
unsupport operand error

### ISSUE THREAD

**Issue by cfjedimaster** [halcy/Mastodon.py#282]
This is most likely my fault as I've been fighting pip all morning, but I'm getting this error running a simple test:

```python
  File "/home/ray/.local/lib/python3.10/site-packages/mastodon/Mastodon.py", line 3694, in __api_request
    method, base_url + endpoint, **kwargs)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Test is just:

```python
from mastodon import Mastodon

mastodon = Mastodon(access_token = 'hard coded access token')
mastodon.toot('Tooting from Python using #mastodonpy !')  

print("Done")
```

**Comment by halcy** [comment]
Hey, when giving a hard coded access token you must also give a base url. Technically you should get an error that says as much. That you’re not getting one is a bug. What version did you use?

**Comment by cfjedimaster** [comment]
Heh, I was just coming here to post that I forgot to set the url - sorry. I just installed your library this morning, so it would be the latest, right?

**Comment by halcy** [comment]
Yeah, if you installed from pip. I THINK i fixed most of this in master, but i’ll use this issue to remind myself to double check.

**Comment by cfjedimaster** [comment]
Cool, thank you for building this.
