### ISSUE TITLE
Restructure code around endpoint structure?

### ISSUE THREAD

**Issue by sneakers-the-rat** [halcy/Mastodon.py#283]
Hello hello!

I'm thinking about a PR and wanted to see if you were interested - I see you note in the TODO that the Mastodon.py file is pretty unwieldy, and wondering if you'd be interested in a rafactor that split the code into multiple modules that reflect the structure of the API endpoint urls? 

As a brief sketch, it would consist of making an `Endpoint` (or whatever name) class that encapsulates the stuff that's split amongst the methods now:

* API Version metadata
* endpoint URL pattern & calling conventions
* request type (`GET`, `POST`, etc.)
* data models (afaik only described in the docs?)

This would go along with another PR i was going to propose as well, to make pydantic models for each of the return types. Defining them in such a way that they can be clearly defined in the metadata for an `Endpoint` object would make documentation a lot easier too i think.

lmk what ya think!

**Comment by halcy** [comment]
This is still a long-term TODO - having type checking would be fantastic (but without breaking existing code, which makes this somewhat finnicky)

**Comment by halcy** [comment]
Actually, probably this goes hand in hand with the return models, so I will close here
