### ISSUE TITLE
Create explicit return models!?

### ISSUE THREAD

**Issue by sneakers-the-rat** [halcy/Mastodon.py#284]
Hello!

Drafted an example of something that I think will make the library easier to use and maintain. If this looks good I'd be happy to make a full pull request that fills out the rest of the models :).

Currently it seems like the return dictionaries are hand-documented as abstract dictionaries in the docs, but within the code there isn't any explicit structure or type hinting to them. 

How about making them with pydantic?

I drafted an example based on the Account dictionary here:
* branch: https://github.com/sneakers-the-rat/Mastodon.py/tree/models
* commit: https://github.com/sneakers-the-rat/Mastodon.py/commit/91a21a7558086ecdaaae42dc2477cc33dea26c3b

### Definition

The structure mimics mastodon's (minimal) nesting structure in its `ActiveRecord` `models` directory. 

With some basic (empty) metaclass:

```python
from pydantic import BaseModel

class MastodonModel(BaseModel):
    """
    Just an empty base class to inherit from for now, but
    could hold any common class methods/attrs. that might
    be needed.
    """

```

The basic pattern of the model looks like this, where I have annotated the type of each of the fields, and copied the description from the docs.

```python
from pydantic import AnyHttpUrl, EmailStr, HttpUrl
from pydantic import Field as _Field

from mastodon.models import MastodonModel

class Account(MastodonModel):
    id: int = _Field(
        description = "Same as <numerical id>"
    )
    username: str = _Field(
        description = "The username (what you @ them with)"
    )
    acct: EmailStr = _Field(
        description = "The user's account name as username@domain (@domain omitted for local users)"
    )
    avatar: HttpUrl = _Field(
        description="URL for their avatar, can be animated"
    )
    avatar_static: HttpUrl = _Field(
        description="URL for their avatar, never animated"
    )
    bot: bool = _Field(
        description="Boolean indicating whether this account is automated."
    )
    created_at: datetime = _Field(
        description="Account creation time"
    )
```

The models also allow using other models as types, so for example the 'source' field has additional structure:

```python
from typing import Optional, List, ClassVar, Literal

PRIVACY = Literal[
    'privacy',
    'unlisted',
    'public'
]

class Source(MastodonModel):
    privacy: PRIVACY = _Field(
        description= "The user's default visibility setting (\"private\", \"unlisted\" or \"public\")"
    )
    sensitive: bool = _Field(
        description="Denotes whether user media should be marked sensitive by default"
    )
    note: str = _Field(
        description="Plain text version of the user's bio"
    )

class Account(MastodonModel):
    source: Optional[Source] = _Field(
        default=None,
        description="Additional information - only present for user dict returned from account_verify_credentials()"
    )
```

The model can also have methods and classmethods, so for example there are a number of places where lists of account dictionaries, so i made a method for that:

```python
    @classmethod
    def from_list(cls, accounts:List[dict]) -> List['Account']:
        return [Account(**account) for account in accounts]
```

### Usage

So then in the `Mastodon.py` file you use the model like this:

Base `Account` usage:

```python
from mastodon.models import Account

class Mastodon:

    @api_version("1.0.0", "1.0.0", __DICT_VERSION_ACCOUNT)
    def account(self, id) -> Account:
        """
        Fetch account information by user `id`.

        Does not require authentication for publicly visible accounts.

        Returns a `account dict`_.
        """
        id = self.__unpack_id(id)
        url = '/api/v1/accounts/{0}'.format(str(id))
        return Account(**self.__api_request('GET', url))

```

List of `Accounts`

```python
from typing import List

class Mastodon:
    def status_reblogged_by(self, id) -> List[Account]:
        """
        Fetch a list of users that have reblogged a status.

        Does not require authentication for publicly visible statuses.

        Returns a list of `account dicts`_.
        """
        id = self.__unpack_id(id)
        url = '/api/v1/statuses/{0}/reblogged_by'.format(str(id))
        return Account.from_list(self.__api_request('GET', url))

```

## Benefits

* **Type Hinting** - I think the biggest reason for this is because it would make the package a lot easier to use! currently all the results are just unhinted dictionaries, so I have to constantly be referring back and forth to the documentation to see what kind of object is returned/what values its fields have/etc. If we wanted to retain backwards compatibility and make them behave as dictionaries as well we could basically do the opposite of what you're doing to make values accessible as attributes and override `__getitem__` to access the `.dict()` method.
* **Testing** - since the models validate their contents, you would be able to simplify the tests substantially while also making them more expressive and robust, by instantiating the model you also test that all the fields are as described.
* **Documentation** - These models would basically replace the existing docs on models, which need to be kept up to date in parallel with updating the queries/etc. for new versions of the API/masto. They would be automatically generated by a sphinx extension that autogenerates from pydantic models :)
* **Schema** - pydantic allows you to create JSON-schema descriptions of models, so these models could be imported by other projects that build off mastodon and used and make downstream documentation & interoperability easier too :)
* **Maintainability/Compatibility** - It could also be possible to make the models represent different versions of the API, so for example, like you already have with documenting different API versions with a function decorator, it would be possible to update If we also were to do https://github.com/halcy/Mastodon.py/issues/283 and wrap up the endpoint in an object, then this could all be done in one place.
* **Extension to query** - so far i've just been thinking about return objects, but we could also do the same thing to specify the fields of a request/query. That would let us basically totally abstract a lot of the logic of the existing request boilerplate.

This would also go well with https://github.com/halcy/Mastodon.py/issues/283 where, like with queries, we could abstract the structure of the library a bit and begin to modularize some of the code to help with maintenance :)

lmk if this seems good and i'll submit a PR!

**Comment by codl** [comment]
I would love type hints.

**Comment by halcy** [comment]
Hey! I am in general a big fan of this (and I also want to add hinting to parameters, for sure, since I don't care about 2.7 anymore, this is now possible).

My main concern is trying to maintain backwards compatibility. I want to avoid, if at all possible, breaking existing code in a big way. If we can do the work here and take in _some_ ugliness to avoid breaking somebody elses code, we should. That means that a few things have to work afterwards still:

* Accessing fields in in a dict type way (returnval["id"]), and generally, converting to dicts
* Pagination for lists
* Maybe some other things?

None of that is impossible to overcome, and a lot could actually be improved this way, like making it more explicit what can and can not be paginated. we have a large suite of tests, as long as they still all pass, all is well. They use recorded data, so you can actually still run them without a masto server, not sure if you've tried yet.

Abstracting away query stuff: That is harder, I think - would still be good to do, esp with stuff like pagination parameters (I've considered adding decorators for some common stuff, specifically unpacking of IDs and pagination), but several endpoints do have custom logic inside that is needed for them to work properly. Maybe a lot of it could be made more generic, though.

**Comment by MinekPo1** [comment]
A possible in-between solution would be `TypedDict`-s, which would result in no logic changes, only annotations. This however would have, however, slightly less benefits.

Also `TypedDicts` are python 3.8+, though via a conditional import and type-hint comments/annotations (via `from __future__ import annotations`) the effect of this could be minimized, though this does seem slightly hacky to me.

**Comment by halcy** [comment]
It was a Major Pain, and still requires some cleanup - but we now have that.
