### ISSUE TITLE
Import of module does not seem to finish (Windows, Python 3.10.0

### ISSUE THREAD

**Issue by guerda** [halcy/Mastodon.py#288]
I'm trying to use Mastodon.py but unfortunately, I cannot import the module
The import command simply does not finish.

h1. Steps to reproduce
1. Install mastodon.py via `pipenv install Mastodon.py==1.8.0`
2. run shell with python `pipenv run python` 
3. Issue `import mastodon` or `from mastodon import Mastodon`

h2. Expected result
The import is successful and you can start using the API.

h2. Current result
The import does not finish and only the cursor is blinking.

h1. Environment
* Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
* Windows 10, 64 bit
* It happened with Mastodon.py 1.7.0 and 1.8.0

![Screenshot of Windows Terminal: Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32; Type "help", "copyright", "credits" or "license" for more information.; from mastodon import Mastodon](https://user-images.githubusercontent.com/230782/205276678-c4fba3f2-3fed-4cd7-acfd-0b80fa12be36.png)

**Comment by halcy** [comment]
That is... weird. I will have a look on a windows machine. Don't usually use pipenv, but you'd figure that'd make no difference. Do you get any backtrace when you hit CTRL+C, to see where it might be stuck?

**Comment by halcy** [comment]
Quickly tried on a windows machine, conda python=3.10 env, and it imports fine for me. Are you familiar with how to use pdb? If so, could you get me a trace of where it hangs, in case it currently does not? Should be something like

`
$ echo from Mastodon import mastodon > test.py
$ python -mpdb test.py
(pdb) c
[wait a bit, hit CTRL+C twice]
(pdb) where
`

**Comment by guerda** [comment]
Thank you for your fast reaction!

> Don't usually use pipenv, but you'd figure that'd make no difference.
Correct, I tried the same with `pip`  and `poetry`. With `poetry` I even got a crash, so it killed the Python session during the import

> Do you get any backtrace when you hit CTRL+C, to see where it might be stuck?
No, I don't get anything. I have to kill the Python process as it is still stuck after > 1 hour. The kill does not yield any backtrace.

I tried to use `pdb` but it does not react to Ctrl+C, either.
![-> from mastodon import Mastodon; (Pdb) c](https://user-images.githubusercontent.com/230782/205290031-aaa0538e-3b0a-42ba-952d-2cbe524842c4.png)
It's stuck there, too. If I kill it, there's no trace, though :( Not sure what is happening

I removed the whole virtual environment already multiple times, but the error is stuck. It seems that you used `python==3.10` which equals to 3.10.8. I will try out the latest bugfix release then.

**Comment by halcy** [comment]
That is... super weird. I'm pretty sure it should not be possible to cause the debugger to hang like that with a module no matter what. I'd say maybe it has problems with I/O somehow, but how? The Mastodon module isn't on some network drive or in some other place that might have weird behaviour, is it?

**Comment by guerda** [comment]
Yeah, I totally agree, it's completely bonkers. I have no problem in importing other libraries.
I have tried it with 3.10.8 now and it has the same effect.

All is on my local drive.

The behavior that CTRL+C is blocked makes me suspicious. Maybe one of the security software pieces is blocking something in the background 🙈

**Comment by halcy** [comment]
Hm, you know, that might be it - maybe some antivirus or ids software is
suspending the IO calls while it does some kind of scan?

**Comment by guerda** [comment]
I will check this behavior on a different machine. It's hard to figure out which security software does what exactly in this point. Up until now, I never had issues with Python packages and that software. 
Thanks for helping to debug this! I'll close this for now.

**Comment by guerda** [comment]
So... with a lot of poor man's debugging (see below), I was able to pinpoint it to the `magic` library.
It seems that in my environment the installation is not complete, because `import magic` fails, too.
If I install `python-magic-bin` additionally, [as indicated in the README](https://github.com/ahupp/python-magic#windows), it works and I can also import `mastodon`.

I am not sure how to fix that, but it seems that the `try` block in `compat.py` around `import magic` doesn't seem to catch this specific issue.

![image](https://user-images.githubusercontent.com/230782/205327745-d5f920a9-45be-4c2e-873b-4eb569cbfcf9.png)

**Comment by halcy** [comment]
That is very interesting, and also very annoying. Does it hang trying to import magic? I guess maybe the hang is in there, then, and I need to add some kind of detection for this case and break if, but also add that pypi package to the requirements for only windows, ideally

**Comment by guerda** [comment]
Yes, manually importing magic hangs too until I installed the binaries.

**Comment by moniesoke** [comment]
same problem here. pip install python-magic-bin solved the problem.

**Comment by halcy** [comment]
Resolved in master
