### ISSUE TITLE
Shouldn't account_search trigger a remote lookup on the server?

### ISSUE THREAD

**Issue by e11bits** [halcy/Mastodon.py#289]
Assume the following code fragment:

```
mastodon = Mastodon(access_token="fosstodon.org_usercred.secret")

account_name = "someuser@mastodon.social"
try:
    account = mastodon.account_lookup(account_name)
    print(account)
except MastodonNotFoundError:
     accounts = mastodon.account_search(account_name)
     if len(accounts) == 1:
         print(accounts[0])
     else:
         print(f"Was not able to find {account_name}")
         print(accounts)
```
My understanding would be:

I'm using `account_lookup` on the fosstodon.org instance to lookup an account from mastodon.social. This account is not known to fosstodon.org (not in the DB I guess) and so I use `account_search` which would trigger the fosstodon.org instance to look that account up on mastodon.social and return the (single) account information.

But what I see instead is, that `account_search` always returns an empty list.

Now when I go the fosstodon.org website, search for `someuser@mastodon.social` it will be found. When I run the code again, `account_lookup` is now successful and returns the right account information.

I assumed it worked this way by reading the doc for `account_search`:

> Mastodon.account_search(q, limit=None, following=False)
> Fetch matching accounts. Will lookup an account remotely if the search term is in the username@domain format and not yet in the database. [...]

**Comment by e11bits** [comment]
This is with version 1.8.0 of Mastodon.py and both instances (fosstodon.org and mastodon.social) are on server version 4.0.2 as of this writing

**Comment by e11bits** [comment]
I think the issue here is, that I had accidentally chosen an account with `'discoverable': False` . What still confuses me is the fact, that I was able to search and find it on the website.

**Comment by halcy** [comment]
I'm actually not sure, but I think it should work, and it is weird if it does not. "discoverable" should only affect trends and such.

**Comment by e11bits** [comment]
Right now I can't reproduce it, but will look at it more closely if happens again.

**Comment by halcy** [comment]
That is interesting. Do the same accounts show up in a search()?

**Comment by e11bits** [comment]
The Webapp also uses resolve=True as far as I can see with search
