### ISSUE TITLE
Is admin.domain_blocks implemented/working?

### ISSUE THREAD

**Issue by danhon** [halcy/Mastodon.py#291]
Trying to write a utility to mass-import servers from a csv blocklist. I get this when I'm trying to pull down the instance blocklist:

`AttributeError: 'Mastodon' object has no attribute 'admin_domain_blocks'
`

I'm connecting with a token that has every single admin scope checked off apart from crypto, and the instance version I'm connecting to is 4.0.2.

This might also be me being really dense and missing something, but VSCode isn't autocompleting all the admin methods, either. 

See also: https://docs.joinmastodon.org/methods/admin/domain_blocks/#get

and 

https://mastodonpy.readthedocs.io/en/stable/_modules/mastodon/admin.html#Mastodon.admin_domain_blocks

Although that said, maybe it looks like this is being caught in a supported version trap?

**Comment by halcy** [comment]
closing, hopefully resolved
