### ISSUE TITLE
admin_domain_blocks ignores pagination parameters.

### ISSUE THREAD

**Issue by defnull** [halcy/Mastodon.py#297]
The `admin_domain_blocks()` API currently only return 100 results and does not allow fetching more results, because the `limit` parameter is ignored and the pagination parameters (`min_id`, `since_id` or `max_id`) are not accepted by the method signature.

**Comment by halcy** [comment]
Hilariously, it will still work via the pagination methods (fetch_*) because those don't actually call the functions but instead use cached parameters to recreate the request, so you can still get to the data, but: whoops. Will fix with next release.

**Comment by halcy** [comment]
fixed in master
