### ISSUE TITLE
Mastodon.py docs incorrect/incomplete

### ISSUE THREAD

**Issue by RedactedCode** [halcy/Mastodon.py#299]
at [](url)https://mastodonpy.readthedocs.io/en/1.8.0/06_accounts.html#following-and-followers, the docs don't show the account_following() method, and place the account_follows() method in the "Reading" section instead of the "Writing" section.

![2022 12 15_15 18 28_mastodonpy readthedocs io_3741270f137cn](https://user-images.githubusercontent.com/31665276/207898187-728bb2d7-fa7d-4328-ba03-56651ee5d940.jpg)

**Comment by halcy** [comment]
oops, that might be an oversight. will fix with next release.

**Comment by FiXato** [comment]
account_following is in the docs, but it's listed under "Accounts", rather than under the "Following and Followers" section. :)
(Came here to report the same issue xD)

**Comment by halcy** [comment]
Moved account_following.

account_follows actually hasn't existed for a while. I'll put in a backwards compat implementation and deprecation warning.
