### ISSUE TITLE
account_follows() & account_followers() can't be paged (maybe)

### ISSUE THREAD

**Issue by RedactedCode** [halcy/Mastodon.py#300]
I'm unclear about the functionality of the account_followers() and account_following() methods.

While each method's parameters appear to include a max_id & min_id like paginated methods, what both actually return are lists of account dicts.
min & max ids can't refer to *user* ids surely?
And if they don't,  I can't see what we should be passing to obtain a fully populated list when calling either method.

If the number of followers/follows an account has exceeds the maximum number that can be returned by a single call (which appears to be 80), we don't seem to have a means to access the remainder.

It's perfectly possible that I have not understood the docs properly, so it would be great to have clarification if this is a problem with me, or Mastodon.py or maybe it's a limitation of the Mastodon API itself

thanks

**Comment by tens0rcat** [comment]
I can't retest right now, but I think the following got the full list:

```
followers = mastodon.account_followers(id = mydata.id)
followers = mastodon.fetch_remaining(followers)
```

**Comment by RedactedCode** [comment]
> I can't retest right now, but I think the following got the full list:
> 
> ```
> followers = mastodon.account_followers(id = mydata.id)
> followers = mastodon.fetch_remaining(followers)
> ```

will test, thx

**Comment by halcy** [comment]
> While each method's parameters appear to include a max_id & min_id like paginated methods, what both actually return are lists of account dicts.
> min & max ids can't refer to user ids surely?
> And if they don't, I can't see what we should be passing to obtain a fully populated list when calling either method.

You're absolutely right - they don't. Mastodons pagination, generally, works via the next / prev headers. The lists Mastodon.py returns have these and other query params annotated as an attribute, to make the fetch_next / fetch_remaining methods work. For SOME endpoints (like timelines!) these will be the IDs of the actual objects returned, but not all. This could probably be  documented better.

For the docs on this as they are now, check here: https://mastodonpy.readthedocs.io/en/stable/01_general.html#pagination

(there is also some documentation in fetch_next and fetch_remaining.... which is currently incorrect. I'll make a note to update it.)

The code tens0rcat gave should work, or if you want more control fetch_next will give you the next page iteratively
