### ISSUE TITLE
timeline_home() limit parameter never returns the actual limit number of items

### ISSUE THREAD

**Issue by netllama** [halcy/Mastodon.py#301]
I'm using version 1.8.0 to request timeline_home() toots on a home timeline that has hundreds of toots available.  If I set the limit parameter to a large number (like 500), I get just 40 toots back.  If I don't specify limit at all, i get just 20.  Neither is returning anything close to the actual total number available:

```
n [46]: latest_timeline0 = t_api.timeline_home(since_id=last_id, limit=500)

In [47]: len(latest_timeline0)
Out[47]: 40

In [48]: latest_timeline1 = t_api.timeline_home(since_id=last_id)

In [49]: len(latest_timeline1)
Out[49]: 20
```

Am I missing some obvious way to make this work better?  I'd expect setting limit=500 to return 500 toots (or whatever number exists up to a maximum of 500).  Returning 40 when I specify 500 seems like a bug.

thanks!

**Comment by halcy** [comment]
Hey,

the 40 statuses is the maximum that most Mastodon accounts will return per page, 20 is how many most Mastodon installs will return if you don't set a limit parameter. The limit is effectively "up to" this many, it'll never return more, but may return less. If you need more than that, you'll have to use pagination - have a look at https://mastodonpy.readthedocs.io/en/latest/01_general.html#pagination for how to do that.

**Comment by netllama** [comment]
Ahh thanks for explaining, that makes more sense.

**Comment by codl** [comment]
limit and other arguments are collected into `params_initial` here: https://github.com/halcy/Mastodon.py/blob/1.8.1/mastodon/timeline.py#L38
