### ISSUE TITLE
Any way to get replies of a toot?

### ISSUE THREAD

**Issue by ujeong1** [halcy/Mastodon.py#304]
It seems like it is limitation of the original Mastodon API, but is there any trick for getting replies of a toot or plan to add this feature in this library?

**Comment by halcy** [comment]
status_context does just that:

https://mastodonpy.readthedocs.io/en/latest/_modules/mastodon/statuses.html#Mastodon.status_context

(“descendants” in the result)

is that what you were looking for or was it something else?

**Comment by ujeong1** [comment]
It seems like what I needed! So I need to search the descendants in the toots I crawled right? Sounds like it might omit some replies if I cannot crawl enough toots in advance.

**Comment by ujeong1** [comment]
Sounds like what I needed! Will it also show the toot from other (federated) servers?

**Comment by halcy** [comment]
In general, yeah, if they’ve been delivered to the server you’re getting data from, which they should be, barring stuff like suspensions
