### ISSUE TITLE
Please specify that m.status_reply() takes a Toot dict, not an ID!

### ISSUE THREAD

**Issue by alexmshepherd** [halcy/Mastodon.py#310]
I was stumped for a while on this:

```
Traceback (most recent call last):
  File "...", line 73, in send_animal
    m.status_reply(winning_reply['id'], "Congratulations! You won!")
  File "...", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File ".../mastodon/utility.py", line 47, in wrapper
    return function(self, *args, **kwargs)
  File ".../mastodon/statuses.py", line 342, in status_reply
    mentioned_accounts[to_status.account.id] = to_status.account.acct
AttributeError: 'int' object has no attribute 'account'
```

It took me a bit of reading the [source code](https://mastodonpy.readthedocs.io/en/stable/_modules/mastodon/statuses.html#Mastodon.status_post) to realise that status_reply() expects a _Toot dict_, not an ID (like most other methods).

Please either change this to reply to Toot IDs, or make it more clear in the documentation.

<3

**Comment by halcy** [comment]
Yeah, it does need the full dictionary. Could fetch it if needed.

I hope that eventually I can overhaul things a bit and make calls type checked so that This Type Of Thing can't happen anymore, in the meantime, probably a note in the docs and explicitly catching this will help. Thanks for reporting.

**Comment by alexmshepherd** [comment]
Thanks :) those kinds of changes would be good, but you're an individual person doing this work for free, who's no doubt become a tad overwhelmed with activity here since November, and your own time and energy are most important. Thanks for all your hard work.

**Comment by alexmshepherd** [comment]
Thanks for the fix :)
