### ISSUE TITLE
Odd since_id and min_id behaviour

### ISSUE THREAD

**Issue by BackSeat** [halcy/Mastodon.py#312]
I'm seeing unexpected results (which I'm sure is a misunderstanding on my part).

With an authenticated API wrapper instance called 'mastodon':

```
now = datetime.datetime.now()
yearago = now - datetime.timedelta(weeks=52)
```

`mastodon.favourites(since_id=yearago, limit=1)'  returns `[]`

`mastodon.favourites(min_id=yearago, limit=1)` returns `[]`

`mastodon.favourites(max_id=now, limit=1)` returns a status (a toot)

Doc says "since_id allows you to specify the smallest id you want in the returned data, but you will still always get the newest data", so I don't understand why specifying an old ID doesn't return anything.

Similarly, "min_id, on the other hand, gives you statuses with that minimum id and newer, starting at the given id" - but it didn't give me any newer status.

Very much appreciate Mastodon.py, just need to understand how this bit works. Once I do, I'll happily re-draft this bit of documentation for your consideration.

**Comment by halcy** [comment]
Hey,

this is an issue in Mastodon.py. I initially assumed snowflake IDs (which can be date paginated) are available for more objects than they are actually available for. Favourites may not actually be snowflake ID paginated (and so cannot take dates for pagination) - unfortunately, that probably means what you are trying to do cannot be done in this way. For the next version, I will have to clean this up and make sure that only functions that can take dates do. Long term, I'd like to have type annotations that clarify what types are valid for which functions, not sure how feasible this is for near term - it is a large effort.

**Comment by BackSeat** [comment]
Thanks for the comment, much appreciated. Now I understand how it works I can code around it.

**Comment by halcy** [comment]
We now have type annotations
