### ISSUE TITLE
Accessing original favorites and reblogs

### ISSUE THREAD

**Issue by Ph-St** [halcy/Mastodon.py#313]
Hi,

the server my bot is running on only sees a fraction of the actual numbers of favorites and reblogs of a certain post when I obtain information on the post with Mastodon.status(id). With the web API, I can access the original post and see the actual favorites and reblogs. Is there any way to do this with mastodon.py? 

Apologies if this is not the right forum for such a question. In this case, could you point me to a better forum?

Many thanks!

**Comment by Ph-St** [comment]
Thanks for the quick reply! By "with the web API" I meant sending GET/POST requests to <original-server>/api/v1/statuses/<id>. 

So I basically have the choice now to either send GET/POST requests with some python module and parse the returning json or I create new mastodon.py objects. I have to see what will be easier in the end, but thanks for the idea of creating a new objects, I didn't think of that.

**Comment by halcy** [comment]
Ah, yeah. In the end, Mastodon.py also doesn't do anything but that, send those requests, but in a nicely wrapped way. If you do try doing it with mastopy and run into issues, let me know, I'm kind of interested in broad compatibility so this is interesting wrt that. Good luck!
