### ISSUE TITLE
Management of symbolik links in media_ and problem with conditional.

### ISSUE THREAD

**Issue by fernand0** [halcy/Mastodon.py#316]
The method `media_post` does not work well when `media_file` is a symbolic link, maybe due to the verificacions in `__load_media_file` are:

             if isinstance(media_file, PurePath):
             if isinstance(media_file, str) and os.path.isfile(media_file):

Which return `False` and then, the image is not loaded.

Moreover, you have:

        if isinstance(media_file, str) and os.path.isfile(media_file):

and

        elif isinstance(media_file, str) and os.path.isfile(media_file):

but they are not different. Maybe I could try to send a patch if you give me a hint of the idea of the elsif part.

**Comment by halcy** [comment]
Yeah, that's a mistake for sure.

I'm actually really confused by why it wouldn't work with a symlink. If it's just "/path/to/file", then it should work (it's a str). If it's a Path object, no matter if it's a Path, PosixPath or actually PurePath, they are all an instanceof(PurePath):

```
(base) halcy@ARARAGI-KUN:~/masto/Mastodon.py$ ls -alh tox2.ini
lrwxrwxrwx 1 halcy halcy 7 Apr 23 19:48 tox2.ini -> tox.ini

(base) halcy@ARARAGI-KUN:~/masto/Mastodon.py$ python
Python 3.9.12 (main, Apr  5 2022, 06:56:58)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import PurePath, Path
>>> a = Path("tox2.ini")
>>> isinstance(a, PurePath)
True
```

Can you show an example of what you're passing to make it False?

**Comment by halcy** [comment]
Oh wait, I see. isfile() won't return true, duh. oof. I'll check how to fix that. Sorry for the confusion.

**Comment by fernand0** [comment]
Sorry for my delay in replying you, maybe my description was not good enough. I've been doing more testing and the problem with symlinks (in my sustem, Fedora 38) seems to be that 
       
        mime_type = self.__guess_type(media_file)

makes mime_type equal to:
      
       inode/symlink

and then, 
     
      mimetypes.guess_extension(mime_type)

returns
     
     None

which cannot be concatenated in:
     
       file_name = "mastodonpyupload_" + str(time.time()) + "_" + str(random_suffix) + mimetypes.guess_extension(mime_type)

generating the error:
     
      Data error: (<class 'TypeError'>, TypeError('can only concatenate str (not "NoneType") to str'),

I can try to investigate further this behavior, but this is, in essence the problem I'm finding now with symlinks.

**Comment by fernand0** [comment]
More details: the problem seems to be with magic module:
    
      magic.from_file('/tmp/2023-01-29_image.png', mime=True)

returns:

     'inode/symlink'

while:

      mimetypes.guess_type('/tmp/2023-01-29_image.png')

returns:

     ('image/png', None)

when the file '/tmp/2023-01-29_image.png' is a symlink to an actual image.

**Comment by halcy** [comment]
That's really weird - it does not in fact happen for me. Might be a filesystem dependent thing. Did you try with the newest version where I added forced path resolution?

**Comment by fernand0** [comment]
Sorry again for the delay. With this newest version it seems to work fine. Thanks!

**Comment by halcy** [comment]
Glad to hear, closing this, then
