### ISSUE TITLE
Using Mastodon.py without aunthentication

### ISSUE THREAD

**Issue by flecktarn121** [halcy/Mastodon.py#330]
Hi,

I would like to access some of the endpoints that do not require authentication. I tried to do something similar to [this](https://github.com/halcy/Mastodon.py/issues/178#issuecomment-504056099), but Mastodon object cannot be instantiated. I get an error telling me that an API base URL is required.

Isn't it possible to use the library to make requests as if they were done manually without any authentication?

**Comment by halcy** [comment]
Hey,

it should work fine if you give an api base url, as the error asks you to - auth or no, the library still needs to know what instance it should be talking to. Can you give that a try?

**Comment by 0xtatsu** [comment]
If you're still struggling with this @flecktarn121 I found that I had to run the `create_app` with the `api_base_url` method and then instantiate Mastodon with `api_base_url` too.

For example:
```py 
API_BASE_URL = "https://mastodon.social"

app = Mastodon.create_app(
    'mdn',
    api_base_url=API_BASE_URL
)

mastodon = Mastodon(api_base_url=API_BASE_URL)
```
Will cc @halcy here in case this solves the issue.

**Comment by codl** [comment]
You should not create an app for anonymous access, apps are for authentication. That snippet should work the same if you remove the call to `create_app`

**Comment by 0xtatsu** [comment]
Oh, thanks for that @codl  didn't realise. Will edit the snippet 🙂

**Comment by halcy** [comment]
Closing this for now - if it's still an issue, please reopen.
