### ISSUE TITLE
About how to "get user ID"

### ISSUE THREAD

**Issue by forestrharumaki** [halcy/Mastodon.py#332]
Hello. Sorry for the machine translation.

I cannot get the account id from the account name (not display name). Is there really no such function?

Thank you in advance for your help.

**Comment by codl** [comment]
see `account_lookup`

https://mastodonpy.readthedocs.io/en/stable/06_accounts.html#mastodon.Mastodon.account_lookup

**Comment by forestrharumaki** [comment]
I overlooked the documentation
Thank you!
