### ISSUE TITLE
AttributeError: 'Mastodon' object has no attribute 'StreamListener'

### ISSUE THREAD

**Issue by getgle** [halcy/Mastodon.py#333]
AttributeError: 'Mastodon' object has no attribute 'StreamListener'

**Comment by getgle** [comment]
Traceback (most recent call last):
  File "/mnt/c/FediSpeaks/main.py", line 28, in <module>
    class Listener(mastodon.StreamListener):
AttributeError: 'Mastodon' object has no attribute 'StreamListener'

**Comment by getgle** [comment]
i dont understand why he dosent have StreamListener

**Comment by andypiper** [comment]
Can you share your code? What version of Mastodon.py are you using? How are you invoking StreamListener?

Does this work for you in the repl?

```
from mastodon.streaming import StreamListener
```

**Comment by halcy** [comment]
Closing this for now - if it's still an issue, please reopen.
