### ISSUE TITLE
Streaming public posts originating from other servers

### ISSUE THREAD

**Issue by jeafreezy** [halcy/Mastodon.py#334]
Thank you for the wonderful library!

I have a bot that boost posts with a specific hashtag. It works fine using the `stream_public()`, however, It usually miss some posts from other servers.

Please is there a way I can provide list of servers I would like to plug to and stream posts from them, for my bot to boost?

There seems to be an endpoint for that on the official docs, but I can't find a way to do that with the library.

https://docs.joinmastodon.org/methods/streaming/
![image](https://user-images.githubusercontent.com/36086324/231582619-5fd1210c-482f-4cc7-ac8f-b9093aaea1cd.png)

Thanks

**Comment by halcy** [comment]
It should ideally not be missing those posts in general, though: The stream_* function make no guarantee that the stream will contain everything in case of reconnect. 

About those endpoints: Seems like quite a few are missing from the library. Thanks for the report, I will add those.

**Comment by jeafreezy** [comment]
Thank you!

**Comment by halcy** [comment]
Actually - some of these are available only via the websocket based API which we currently don't support. May add that eventually. For now, the one i can add is public/remote

**Comment by jeafreezy** [comment]
I think remote and public will be awesome 👌

**Comment by halcy** [comment]
Fixed in master
