### ISSUE TITLE
examples of use in documentation

### ISSUE THREAD

**Issue by snapsnapsnap** [halcy/Mastodon.py#337]
is it possible to get som practical examples of how to use things in the documentation?  or if this is somewhere I can not find it, please point me in the correct direction. hope this question is ok as a new issue, I can not find anywhere else to ask. maybe that should be my second question, is there a forum, or channel anywhere for discussion or questions? (I am sure are everyone is exiting twitter this will be usefull).

**Comment by halcy** [comment]
I put this link in the readme and docs.
