### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by mispp** [halcy/Mastodon.py#346]
Found a possible bug: making a bot in the same VM as the gotosocial instance and connecting locally via http.

Traceback (most recent call last):
  File "/opt/bot/scripts/./bot-01-define-app.py", line 10, in <module>
    Mastodon.create_app(
  File "/home/bot/.local/lib/python3.10/site-packages/mastodon/authentication.py", line 50, in create_app
    api_base_url = Mastodon.__protocolize(api_base_url)
  File "/home/bot/.local/lib/python3.10/site-packages/mastodon/internals.py", line 646, in __protocolize
    if not base_url.startswith("http://") and not base_url.startswith("https://"):

**Comment by halcy** [comment]
Hm! Could you post the code you are running? What does the full call to create_app look like?

**Comment by mispp** [comment]
```
#!/bin/python3

import argparse

from mastodon import Mastodon

api_base_url = 'http://localhost:8080',
nuwwibot_clientcred = 'bot_clientcred.secret'

Mastodon.create_app(
    'bot',
    api_base_url = api_base_url,
    to_file = bot_clientcred
)

```

**Comment by codl** [comment]
you have a stray comma on the line
```python
api_base_url = 'http://localhost:8080',
```
which makes it equivalent to
```python
api_base_url = ('http://localhost:8080', )
```
please remove the comma and try again

**Comment by mispp** [comment]
thanks @codl 

i cant believe i missed that...
