### ISSUE TITLE
Only "read" scope is granted on login

### ISSUE THREAD

**Issue by encarsia** [halcy/Mastodon.py#35]
Trying to login (on octodon.social instance) failes with an API error thrown:

`mastodon.Mastodon.MastodonAPIError: Granted scopes "read" differ from requested scopes "follow read write".`

The login is successful when only asking for the "read" scope but then only read functions can be used, of course.
App creation and registration work and ...oauth/authorized_applications also confirms that read, write and follow privilege is enabled.

This worked before. It might be relevant that octodon was updated to Mastodon v1.1.2 yesterday...?

**Comment by azillion** [comment]
Try this
`auth_request_url(client_id, redirect_uris="urn:ietf:wg:oauth:2.0:oob", scopes=['read', 'write', 'follow'])`
The returned url should request all the scopes.

**Comment by encarsia** [comment]
> The returned url should request all the scopes.

It does, I authorize, then on login the error occurs. Then tried again with a fresh registered app, still the same, only read scope is granted.

**Comment by TakesxiSximada** [comment]
I also encountered the same problem. It seems that you can not pass the scope to the log_in () request. I solved it as follows.

```
@@ -208,10 +208,12 @@ class Mastodon:
             params['grant_type'] = 'refresh_token'
         else:
             raise MastodonIllegalArgumentError('Invalid arguments given. username and password or code are required.')
-
+
         params['client_id'] = self.client_id
         params['client_secret'] = self.client_secret
-
+        if scopes:
+            params['scope'] = ' '.join(scopes)
+

```
https://github.com/TakesxiSximada/Mastodon.py/commit/dd21abde627414458bea3e8220b8396087a56057

**Comment by azillion** [comment]
@TakesxiSximada Scope is intentionally not passed
https://github.com/tootsuite/documentation/blob/master/Using-the-API/Testing-with-cURL.md
The API doesn't accept scope as a parameter.
https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples#post---oauthtoken

Not sure what the issue is but passing the scope in the login request should have no effect.

**Comment by azillion** [comment]
Have you tried following this example?

https://github.com/halcy/Mastodon.py/pull/27

**Comment by halcy** [comment]
You used to have to request scopes on login, but I don't think you do anymore (neither for oauth nor for sign_in). I'm not sure why the granted scopes would differ, though, if the apps scopes are set correctly.

**Comment by CheapSeth** [comment]
I can confirm I have the same issue when generating a new user token.
My instance it at the latest release (v1.2) but I got the exact same error before updating.

Here is the code I run:

```python
mastodon = Mastodon(client_id="apptoken.cfg",
                    api_base_url=mastodon_instance)

mastodon.log_in(username,
                password,
                to_file="usertoken.cfg")
```

where username, password and mastodon_instance are set to the appropriate values are set in a configuration file.

The error appears to be the same:

```bash
Traceback (most recent call last):
  File "create_user_token.py", line 13, in <module>
    to_file="usertoken.cfg")
  File "/home/cheapseth/Projets/crypto/pricebot/thirdparty/mastodon/Mastodon.py", line 234, in log_in
    raise MastodonAPIError('Granted scopes "' + received_scopes + '" differ from requested scopes "' + requested_scopes + '".')
mastodon.Mastodon.MastodonAPIError: Granted scopes "read" differ from requested scopes "follow read write".
```

**Comment by azillion** [comment]
I'll try this tomorrow using a username and password. The oauth version should work though but I'll investigate this issue

**Comment by CheapSeth** [comment]
Thank you very much for your time, I can confirm the issue is resolved on my end

**Comment by encarsia** [comment]
I agree, thank you. That works for me, too.
