### ISSUE TITLE
MastodonVersionError: Version check failed (Need version 1.1.0)

### ISSUE THREAD

**Issue by chrisschm** [halcy/Mastodon.py#351]
I am developing a bot, running on my own Instance ([social.jcs-net.de](https://social.jcs-net.de) Mastodon v4.1.4) and thougt i should migrate my VM to a new bare metal Server inside a lxc container on proxmox. It was running before insite SOHO-NAS VM. But then i can't get it working anymore. Tryed Debian (bullseye and bookworm) and Ubuntu (Jammy Jellyfish and Lunar Lobster).

It was still running in Windows (powershell) and for that reason, i tryed to start a clean installation of a dev-environment inside a WSL2 with the same error.

```
Windows 10 - WSL2 - Ubuntu 22.04.2 LTS
Python 3.10.6

Package            Version
------------------ --------
beautifulsoup4     4.12.2
blurhash           1.1.4
certifi            2023.5.7
charset-normalizer 3.2.0
decorator          5.1.1
idna               3.4
Mastodon.py        1.8.1
Pillow             10.0.0
pip                22.0.2
python-dateutil    2.8.2
python-magic       0.4.27
requests           2.31.0
setuptools         59.6.0
six                1.16.0
soupsieve          2.4.1
urllib3            2.0.3
```
I am using a venv environment.
Error:

```
Traceback (most recent call last):
  File "/home/cs/python/mastoinfo/MastoInfoBot.py", line 181, in <module>
    m.stream_user(Listener())
  File "/home/cs/python/mastoinfo/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/cs/python/mastoinfo/lib/python3.10/site-packages/mastodon/utility.py", line 46, in wrapper
    raise MastodonVersionError(f"Version check failed (Need version {version})")
mastodon.errors.MastodonVersionError: Version check failed (Need version 1.1.0)
```

**Comment by halcy** [comment]
Hi,

could you please post the code that is causing the error? What does line 181 and surroundings of /home/cs/python/mastoinfo/MastoInfoBot.py look like? And do you know which version of Mastodon.py you have installed?

**Comment by chrisschm** [comment]
Sure. The version is 1.8.1 (standing above in the package list) and here comes the coat for my bot.

```
import mastodon
from mastodon import Mastodon
import os

absFilePath = os.path.abspath(__file__)
ScriptPath, ScriptFilename = os.path.split(absFilePath)
m = Mastodon(access_token='usercred.secret', api_base_url=ScriptPath)

class Listener(mastodon.StreamListener):
    def on_notification(self, notification):
        #some code

m.stream_user(Listener())
```

The last line here is line 181 inside the bot.

**Comment by chrisschm** [comment]
I've had a look into some of the Mastodon.py files and it seems it messed up with NEW_LINE between LF and CRLF. Could you have a look at this issue and if so do a new release without? Don't know if that fixes the issue..

**Comment by halcy** [comment]
Ah, oh bother. Thanks for debugging that - I will have a look and hopefully fix that. However: it will take a while, I‘m currently busy with other things.

**Comment by chrisschm** [comment]
you're welcome.

And i could fix the problem either - my fault, sorry. When you view the code above, you'll see that i was using in `api_base_url=ScriptPath` the local path instead the Mastodon website URL. I thought its taken by the usercred.secret file and here it would need the path of the credentials file.

I'm closing the issue and hoping this may help you with upcoming issues. Shame on me.
