### ISSUE TITLE
Add Citation for Mastodon.py

### ISSUE THREAD

**Issue by hauschke** [halcy/Mastodon.py#353]
It seems obvious that Mastodon.py will be used a lot in research and research infrastructure. It seems to me like it would be a good idea to submit it to https://joss.theoj.org/ or at least to add a citation file (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files). Or using Zenodo (https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content).

PS: Thanks for Mastodon.py, it's really extremely easy to use!

**Comment by halcy** [comment]
Sure, I can add something. Think a bibtech snippet would work?

**Comment by hauschke** [comment]
I personally would always try to get a DOI, but https://github.com/J535D165/pyalex/blob/main/CITATION.cff is an example of something inside your repo that works. A BibTeX snippet will be automaticalle generated from this.

**Comment by halcy** [comment]
Added a .cff file for now, thank you for the suggestion. Maybe I will try to do a publication... at some point.
