### ISSUE TITLE
Event on mentioned?

### ISSUE THREAD

**Issue by writeblankspace** [halcy/Mastodon.py#359]
Does Mastodon.py have events, so when the bot is mentioned certain code will be run?

**Comment by halcy** [comment]
You can use the streamign API to achieve some kind of event based workflow, but if you're specifically building a bot, you might be better served by some higher level framework like [Ananas](https://github.com/chr-1x/ananas)

**Comment by halcy** [comment]
Closing this for now - if you have more questions, feel free to hit me up here or on masto
