### ISSUE TITLE
Unable to login to other instances

### ISSUE THREAD

**Issue by FlyMyPG** [halcy/Mastodon.py#36]
The log_in() method always fails when passed a known-good login.  It appears to always try to login to mastodon.social, even when passed another instance.

Please show a successful login on another instance and post sample code.

**Comment by azillion** [comment]
I tested with mastodon.cloud and it worked fine
A new app must be registered for each new instance your user tries to login to.
```python
import requests
from mastodon import Mastodon

# Register app - only once!
# A new app must be registered for each new instance your user tries to login to.
new_masto_app = Mastodon.create_app(
     'pytooterapp2',
     api_base_url="https://mastodon.cloud",
     to_file = 'pytooter_clientcred.txt'
)

# Setup client
mastodon_client = Mastodon(
    client_id = 'pytooter_clientcred.txt',
    api_base_url="https://mastodon.cloud"
)

# Log in  - either every time, or use persisted
r = mastodon_client.log_in(
    username="Your_Username",
    password="Your_Password",
    redirect_uri = "urn:ietf:wg:oauth:2.0:oob",
    to_file = 'pytooter_usercred.txt'
)

print(r)
```

**Comment by FlyMyPG** [comment]
Thanks!  I had missed one of the api_base_url parameters.

All function parameter descriptions, and this example, should be added to the docs.

**Comment by azillion** [comment]
You're welcome to make a pull request for that, if not then I'll try to do it eventually.

**Comment by FlyMyPG** [comment]
I was considering doing just that, but most parameters get passed to libraries I haven't used, so there'd be another level of digging involved, with associated guesses and errors.

I'm working on a script to pull all toots I've written on a given account/instance.  It works great on new accounts, but seems to always stop at 400 (20 calls) on older accounts:

    toots=[]
    t = mastodon.timeline_home()  # Gets most recent first, oldest last
    while len(t) > 0:
        toots += t
        t = mastodon.timeline_home(max_id=t[-1]['id'])

Any clue why the above quits at 400?

**Comment by azillion** [comment]
I think this issue can be closed
Feel free to open an issue on that question so others can look at it too. Nothing in your code stands out to me though, might be an issue with @tootsuite/mastodon 's  API

**Comment by FlyMyPG** [comment]
Not A Bug

**Comment by azillion** [comment]
Not sure why it'd stop at 20 calls then

**Comment by FlyMyPG** [comment]
I didn't stop: The Mastodon server stopped returning data after 20 calls (each of which returned 20 toots).

**Comment by FlyMyPG** [comment]
If I knew Ruby I'd try to dig through the source to find out...

**Comment by azillion** [comment]
Yeah I don't know ruby either, I'd just recommend making an issue on their repo, hopefully someone has an answer about it
