### ISSUE TITLE
Deprecate visibility parameter value `private` and use `followers_only` instead

### ISSUE THREAD

**Issue by ashwinvis** [halcy/Mastodon.py#363]
## Context
While trying to read the docs,  I assumed `private` meant direct messages and got confused

Screenshot of the [online docs:](https://mastodonpy.readthedocs.io/en/stable/05_statuses.html#status-post) to see how it reads now
> ![image](https://github.com/halcy/Mastodon.py/assets/9155111/d9d91a09-8a03-4f6f-bedf-5656fba60778)
 
 I think the problem was 2 fold
1. It was not formatted. I have this fixed in #362 
2. The Mastodon web UI and the [API docs](https://docs.joinmastodon.org/user/posting/) mentions `"followers_only"` and not `"private"`. This can be misleading.

I wonder if we can use `followers_only` as the visibility parameter value. We can still support `private` for a while with a warning.

**Comment by codl** [comment]
The Mastodon API does use `private`, and given that this library is a fairly direct wrapper over the API, I don't think changing the terms would be a good idea. The documentation you've linked is the end-user documentation, not the [API documentation](https://docs.joinmastodon.org/methods/statuses/#create).

I'm all for formatting the docs better, I'd go one step further and mention user-facing terms in the documentation as well, something like

> * `'direct'` - post will be visible only to mentioned users, known in Mastodon's UI as "Mentioned users only"
> * `'private'` - post will be visible only to followers, known in Mastodon's UI as "Followers only"
> * ...

**Comment by ashwinvis** [comment]
Done

**Comment by halcy** [comment]
closed by your PR! and thank you so much for that!
