### ISSUE TITLE
module is installed, but missing library stubs or py.typed marker

### ISSUE THREAD

**Issue by ZeeD** [halcy/Mastodon.py#364]
Hi.
It seems that, while skimming at the code I see it seems well annotated, the distributed library does not expose it.
From what I know from [pep 561](https://peps.python.org/pep-0561/) it could be enough to just add an empty `py.typed` in the main package and publish it

**Comment by halcy** [comment]
Do you have any information about how that would work in practice / tooling side? Do I need to run something to export the type information on build, or should the build system just do that?

**Comment by ZeeD** [comment]
Well, from a cursory glance at [your pyproject.toml](https://github.com/halcy/Mastodon.py/blob/master/pyproject.toml#L2) it seems that you relies on `setuptools` to build your packages.

If you use the current version of setuptools (69.x.x) it should be enough to just create an empty `mastodon/py.typed` file in your repo and it should autodetect and include it in the package.

Otherwise, according to https://github.com/pypa/setuptools/issues/3136 it should be necessary to add `include_package_data = True` and `options.package_data` `* = py.typed`

If you share how you build the packages (what commands do you launch, how are they set up, etc) I may try to do the necessary changes

**Comment by halcy** [comment]
I usually just ``python setup.py sdist bdist_wheel``. I will try adding the file.

**Comment by halcy** [comment]
added marker file, hopefully that does the trick

**Comment by ZeeD** [comment]
Hi!
Thank you for the change.
I've just cloned and created a package from main and - indeed - the `py.typed` is here:

```
$ python3.12 setup.py sdist bdist_wheel
...
$ unzip -l dist/Mastodon.py-1.8.1-py3-none-any.whl
Archive:  dist/Mastodon.py-1.8.1-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
...
        0  02-12-2024 10:50   mastodon/py.typed
...
---------                     -------
   385403                     40 files
```

**Comment by jernst** [comment]
Could you re-publish the package with the `py.typed` to PyPi?
