### ISSUE TITLE
scopes = ['read', 'write'] is ret, but the generated url sill contains '+follow+push'

### ISSUE THREAD

**Issue by fabiscafe** [halcy/Mastodon.py#365]
Hi. I'm currently trying to connect my setup to mastodon(mstdn.social). I only need read and write access.
For some reasons the moment I remove follow and push from the scopes the url will not work anymore.

After a bit more try and error, it seems to be the case that while the scopes are reduced, the url part generated by `.auth_request_url()` always contains `&scope=read+write+follow+push`

If I go with: …`.auth_request_url().replace("+follow+push","")` everything works fine. 

This is with mastodon.py 1.8.1

**Comment by halcy** [comment]
Hey,

could you post the code you are using? Are you passing the scopes you want to auth_request_url?

**Comment by fabiscafe** [comment]
Sorry it took me so long.

## Scopes-Test "test.py"

For example:

```
from mastodon import Mastodon

app_name = "fedistester"
instance_url = "https://mstdn.social"
mascopes = ['read', 'write']


# Register app
setup_app = Mastodon.create_app(
    app_name,
    scopes = mascopes,
    redirect_uris = None,
    website = "https://example.com",
    to_file = None,
    api_base_url = instance_url,
    request_timeout = 300,
    session = None,
    user_agent = 'mastodonpy'
)
setup_api = Mastodon(
    client_id = setup_app[0],
    client_secret = setup_app[1],
    api_base_url = instance_url
)

print("scopes defined:\t\t", mascopes)
# cut out the scope part of the url
the_url = setup_api.auth_request_url()
url_scope = the_url[the_url.index("&scope=") + len("&scope="):]
url_scope = url_scope[:url_scope.index("&") + len("&") -1 ]
print("scopes requested:\t", url_scope)
print()
if int(url_scope.count('+'))+1 != len(mascopes):
    print("Following url might *not* work")
else:
    print("Following url might work")

print(the_url)
```

Will generate:
```
python ./test.py
scopes defined:		 ['read', 'write']
scopes requested:	 read+write+follow+push

Following url might *not* work
https://mstdn.social/oauth/author…&scope=read+write+follow+push&f…
```
---------

So while I only define read and write, it will ask for read, write, follow and push. The generated url wont work:

![grafik](https://github.com/halcy/Mastodon.py/assets/18744080/c42e9d8e-510a-4b5a-bde8-158a1546be2d)

**Comment by codl** [comment]
you need to pass the scopes you want to `auth_request_url`

```diff
- the_url = setup_api.auth_request_url()
+ the_url = setup_api.auth_request_url(scopes=mascopes)
```

**Comment by fabiscafe** [comment]
@codl Thanks. that works! But then what does the scopes in `mastodon.create_app()` do?

I might understand something completely wrong, as very noobish beginner in programming, I just looked it up via this:
https://mastodonpy.readthedocs.io/en/stable/04_auth.html#app-registration-and-information

**Comment by halcy** [comment]
Essentially, the scopes in create_app set what scopes your app is allowed to request, and then the scopes in the login flow set what you actually request. I am not actually sure if mastodon lets you drop some (eg app can read and write, but you just request read), or if they have to match, tbh. Best to just use the same.

**Comment by fabiscafe** [comment]
@halcy Now I do understand. Thanks both of you! I'll close this one now. :+1:
