### ISSUE TITLE
api.media_post does not halt until done processing

### ISSUE THREAD

**Issue by pudup** [halcy/Mastodon.py#377]
Sometimes when I upload an image using api.media_post and then a status_post, I'm hit with a

``` MastodonAPIError 422. Can't post unprocessed file. Try again later! ```

That's not the exact error but it's more or less that.

I can successfully post after waiting a few seconds so I either do a try catch for ```MastodonAPIError``` and then sleep for a few seconds and try again until it succeeds. 

The error is unpredictable because the file being uploaded comes from an unpredictable API so I cannot in advance determine how long it might take to process.

Is there a way for media_post to halt itself until it's done? Is that what synchronous is for?

**Comment by codl** [comment]
Yes, that is what `synchronous` does.

You can also use the (undocumented?) `Mastodon.media(id)` method to check if the media is done processing (in which case the returned dict will have a `url`). This is in fact what `synchronous` does behind the scenes.

**Comment by pudup** [comment]
That helps a lot thanks
