### ISSUE TITLE
sensitive parameter (status_post) is not (only) boolean

### ISSUE THREAD

**Issue by buerviper** [halcy/Mastodon.py#386]
Documentation says
> The sensitive boolean decides whether or not media attached to the post should be marked as sensitive, which hides it by default on the Mastodon web front-end.

However, I found that it is not only boolean, but in addition reacts to strings.

`mastodon.status_post("test", media_ids = [media uploaded previously], sensitive = True)`
results in media marked as sensitive.

`mastodon.status_post(... sensitive = False)`
results in media not marked as sensitive.

`mastodon.status_post(... sensitive = "this is a string")`
results in media marked as sensitive (as if it checks for 'bool(string)').

`mastodon.status_post(... sensitive = "false")`
results in media not marked as sensitive.

`mastodon.status_post(... sensitive = "False")`
results in media marked as sensitive.

So the parameter checks EITHER for the boolean OR for the string `"false"` (case sensitive!). Probably the documentation should reflect that? I found it from a weird bug in one of my programs, so not sure if it is relevant.

**Comment by halcy** [comment]
This is kind of from how parameters are passed to the API (directly). It's... weird, I agree, yeah. I wonder if we should do something about it. We do have extensive type annotations now, but I feel that maybe this is best left alone / left to the linter (which should catch bugs like that for you, hopefully, once the annotated version is out)

**Comment by buerviper** [comment]
I mean it is a very specific bug, that I only found because a small program I wrote incorrectly used the strings "true" or "false", and somehow, Mastodon until 4.3 seemed to be fine with that, but now it complained.

I just wanted to file it for completeness sake, because I didn't find any info on it anywhere else.

**Comment by halcy** [comment]
yeah, if you're alright with it, I would close this - it doesn't seem worth the effort to try to catch this inside of python (it just isn't set up for it).

If you do think it'd be worth to try and solve, feel free to reopen, but I don't know what a good approach would be except purposely coerce every bool argument, which seems like a lot
