### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Gargron** [halcy/Mastodon.py#4]
You could parse the Link header to get previous/next result sets for connections

**Comment by halcy** [comment]
I really should add an easy way to go forward / backward, possibly by just returning an iterator. I wonder how hard that would be.

**Comment by azillion** [comment]
I can get started on this.

**Comment by azillion** [comment]
Can you explain a bit more how you're wanting this feature to work. And what you want to be returned to the client. I have something that works, it returns an object that is iterable, with a response attribute if you want the plain response. Is that what you're thinking?

**Comment by halcy** [comment]
That sounds fairly good! Can you put up a PR so that everybody can check it out?

**Comment by azillion** [comment]
Yup, I can try and make the PR today.

**Comment by Lertsenem** [comment]
While you're resolving this, is there any workaround to get all followers from an account? I tried setting the 'limit' parameter, but I can't get more than 80 followers.

**Comment by halcy** [comment]
You can essentially follow the "link" header manually, for now, and that's probably it, until somebody gets around to working this all out (I presently have little time to do it myself, sorry)

**Comment by halcy** [comment]
Resolved by d4b37995fea40320c1971ea8bd747fc9ece9c368
