### ISSUE TITLE
"follow_by_uri" does not appear to be supported.

### ISSUE THREAD

**Issue by FlyMyPG** [halcy/Mastodon.py#40]
The REST API item "[follow_by_uri](http://www.rubydoc.info/gems/mastodon-api/Mastodon/REST/Accounts#follow_by_uri-instance_method)" does not appear to be supported.

Is this intentional?  What other API items are missing?

**Comment by halcy** [comment]
It is not intentional - just some parts are not implemented. If you want, feel free to have a go at it.

**Comment by halcy** [comment]
Fixed by PR.
