### ISSUE TITLE
ReadMyToots.py

### ISSUE THREAD

**Issue by FlyMyPG** [halcy/Mastodon.py#42]
I've written my first working script based on Mastodon.py.  It's called "[ReadMyToots](https://gist.github.com/FlyMyPG/41b273afe525541c2bc7334d9384b134)", and it pulls down all toots you've written, converts them to plain text, then saves them in chronological order (earliest toot first) to a file.

This is a feature that should probably be built into Mastodon, but until that day comes, this script should help.

I created it to make it easier to catch up with folks I follow: Reading a text file of their toots in the order written is much faster and easier than the web interface.

It also works great for the stories some folks are tooting, [such as this one](https://gist.githubusercontent.com/FlyMyPG/a746d50f1c79bbd85de5849a35d73248/raw/0368d8038626746977b14e3d94a944b3f36a949e/Redshirt27@tenforward.social.txt) by [Redshirt27](https://tenforward.social/@Redshirt27).

As the first working version, I'm certain there's tons of room for improvement.  Please let me know in the comments!

_How do I set a "Help Wanted" label on this?_

**Comment by halcy** [comment]
I'm not sure this is the right place for this - maybe ask on mastodon in some appropriate hashtag?
