### ISSUE TITLE
double exceptions on log_in failure (v1.0.6)

### ISSUE THREAD

**Issue by brrzap** [halcy/Mastodon.py#43]
when given a bad password or email, log_in() produces the proper MastodonIllegalArgumentError and an additional MastodonAPIError.  i can only seem to catch one of them; traceback and raw html from the second gets dumped all over the screen.  this is in a terminal client, so several screenfuls of unavoidable junk text is less than userfriendly.

this is a change from earlier versions; neither v1.0.2 nor v1.0.5 throw the extra MastodonAPIError.

**Comment by halcy** [comment]
I think that was someones debugging edits that made it in accidentally. Hopefully fixed by  6f48c15.
