### ISSUE TITLE
Requests can hang forever, specifically in media upload

### ISSUE THREAD

**Issue by halcy** [halcy/Mastodon.py#5]
Possibly missing timeout settings?

**Comment by Gargron** [comment]
Do you have suggestions for a timeout that would not break media uploads of 4MB max?

**Comment by Gargron** [comment]
Well, I just added 30s timeouts.. realistically something like 90-120s max?

**Comment by halcy** [comment]
30s is maybe a bit low for people on mobile. I'll add a client side timeout for the library, probably, set to something absurdly high, just to catch hangs-forever kind of problems

**Comment by halcy** [comment]
Fixed in 19a1b014d4bfa721c5f091c47b3d6d12bfc32664
