### ISSUE TITLE
hashtag streams never show updates

### ISSUE THREAD

**Issue by brrzap** [halcy/Mastodon.py#50]
it's not a server issue; they can be seen with `curl`:

    curl --header "Authorization: Bearer ${TOKEN}" -sS 'https://mastodon.social/api/v1/streaming/hashtag?tag=mastodon'

logging shows the requests connection to the proper endpoint but it's unclear if the tag is getting specified properly.  successfully streaming to the 'public' endpoint looks basically the same:

    2017-05-08 23:03:55|requests.packages.urllib3.connectionpool|MainProcess|DEBUG| Starting new HTTPS connection (1): mastodon.social
    2017-05-08 23:04:10|requests.packages.urllib3.connectionpool|MainProcess|DEBUG| https://mastodon.social:443 "GET /api/v1/streaming/hashtag HTTP/1.1" 200 None

(on the plus side, they don't seem to be throwing errors, either.)

**Comment by brrzap** [comment]
this silently fails:

    mymastodon.hashtag_stream(tag, listener)

this works:

    endpt = "/api/v1/streaming/hashtag?tag={}".format(tag)
    mymastodon._Mastodon__stream(endpt, listener)

**Comment by halcy** [comment]
Seems like streams are GET requests and the code as it is does POST, maybe.

I'll fix it accordingly.
