### ISSUE TITLE
Test with https by default

### ISSUE THREAD

**Issue by framawiki** [halcy/Mastodon.py#54]
I think that the library must try to use https instead of http, simply because by definition it's more secure.

» it must try to connect to "https://framapiaf.org" if "http://framapiaf.org" is configured. If it works, he must use it. If request fails, it toggles on http only.

It would be particularly useful because lots of instances only accept https requests and deny http.
It would avoid much research for developers if like me they forget to type the S.

```
>>> mastodon_api = Mastodon(
...      client_id = "mtt_mastodon_client.secret",
...      access_token = "mtt_mastodon_user.secret",
...      ratelimit_method = "wait",
...      api_base_url = "http://framapiaf.org"
... )
>>> mastodon_api.status_post('test', visibility="private")
mastodon.Mastodon.MastodonAPIError: Endpoint not found.
>>> 
>>> mastodon_api = Mastodon(
...      client_id = "mtt_mastodon_client.secret",
...      access_token = "mtt_mastodon_user.secret",
...      ratelimit_method = "wait",
...      api_base_url = "https://framapiaf.org"
... )
>>> mastodon_api.status_post('test', visibility="private")
{...}
```

**Comment by brrzap** [comment]
changing the behavior of `api_base_url` to rewrite the user's specified protocol is probably a bad idea.  the user may want `http://` rather than `https://` for some reason; the API shouldn't try to second-guess here.

but an alternate keyword argument (perhaps `instance_hostname`?) could be provided that would internally set `api_base_url` in the manner you suggest -- ie, try with `https://` first, and fallback to `http://` on certain errors.

**Comment by halcy** [comment]
What I'm considering is coercing the URL to https and adding an "allow http" type keyword argument to turn that behaviour off (that is False by default).

This is a breaking change, but probably breaks very little deployed code... it's not exactly super high priority, though.

**Comment by brrzap** [comment]
i'm pretty solidly against any breaking change here for what boils down to user error.

what if the default-to-https behavior is only applied when `api_base_url` doesn't include the protocol?   if the user specifies a protocol, they get it, and no fallback.  if they instead pass `instance.example.org` then the library can try protocols in order.
