### ISSUE TITLE
Visibility issue

### ISSUE THREAD

**Issue by thor-the-norseman** [halcy/Mastodon.py#55]
I'm using feed2toot which uses Mastodon.py and I have a number of news bots on my instance. I just set the default post visibility to Unlisted on their accounts, and noticed that feed2toot wasn't honoring the setting, so I went to look at the source code.

In the source code, I found that feed2toot uses the .toot() call, and according to Mastodon.py's documentation, the default for this is binary: Posts are either public or followers-only, depending on whether or not the account is locked. But this isn't the right behavior. What it should do is to look at the default visibility that the user has set, and base it on that.

I can't stop my bots from filling up the local timeline without this, so getting it fixed is kind of urgent...

**Comment by halcy** [comment]
That part of the documentation is from before there were more than two privacy settings (good catch). What it SHOULD be doing is defaulting to whatever visibility is the account default. If it does not do that, then that's weird... I'll look at it. In the meanwhile, you can patch your local copy of feed2toot to explicitly set visibility.

(The toot() method should also probably not be used in production code, maybe that should be noted in the docs. It's mostly for messing about.)

**Comment by halcy** [comment]
Brief update: It is in fact the status of your account being locked or no that determines default visibility.

https://github.com/tootsuite/mastodon/blob/master/app/models/status.rb#L269

I might put in an issue to change this, since a visibility setting is now a thing, and is exposed through the API. We'll see.

**Comment by halcy** [comment]
Further updates here: This has been changed with mastodon 1.6 (Compare https://github.com/tootsuite/mastodon/pull/4861 ). Code does not need a fix, probably. Documentation does, should mention pre-1.6 as well as post-1.6 behaviour.
