### ISSUE TITLE
2FA / TOTP

### ISSUE THREAD

**Issue by mcrosson** [halcy/Mastodon.py#56]
Is there a 'correct' way to setup the library when using an account with 2FA/TOTP enabled?

I tried a few forms and could not get the authentication/login to work correctly.

**Comment by brrzap** [comment]
i can't speak to correctness, but this is how [tootstream](https://github.com/magicalraccoon/tootstream) enables 2FA:

1. register the app with the instance (call `Mastodon.create_app()`)
2. instantiate a temporary Mastodon object with those credentials
3. display the login link (call `Mastodon.auth_request_url()`)
4. get the code from the user
5. get the auth token (call `Mastodon.login()` with the user's code) (no email/password here -- those are only needed for non-2FA)

if you store the auth token and app credentials, future runs can skip these steps and directly instantiate a logged-in Mastodon object.

**Comment by mcrosson** [comment]
Thank you for the response. I was able to get it working. :)

If you ever need another example: https://gitlab.com/photog.social/mastodon_bot/commit/3eeaad02b50e98b2e2ed60461d52085f80c938e4
