### ISSUE TITLE
copy&paste errors?

### ISSUE THREAD

**Issue by HLT** [halcy/Mastodon.py#57]
are the following lines in mastodon.py correct?

(761)  params = previous_page[-1]['_pagination_next']  -- shouldn't that be "[0]" instead of "[-1]"
(785)  params = next_page[-1]['_pagination_prev'] 

(972)  next_params['max_id'] = int(matchgroups.group(1)) -- shouldn't that be 'since_id' instead of 'max_id'?
(984)  prev_params['max_id'] = int(matchgroups.group(1))

**Comment by halcy** [comment]
I think it's... the other way around? I'll have to look at it.

**Comment by HLT** [comment]
yeah may be. as i understand it, the pagination_next should be in the last entry(-1) of the page and the pagination_prev should be in the first entry(0) of the page.
