### ISSUE TITLE
please consider dropping "dateutils"

### ISSUE THREAD

**Issue by ng-0** [halcy/Mastodon.py#63]
I'm currently packaging Mastodon.py for our package manager and distro (Guix, GuixSD) and had to notice you are mandatory depending on a python package which has last seen a (pypi- ) release in 2013.

Could you drop this in favor of more actively maintained python packages?
Isn't "dateutil" part of the python standard (2 and 3)?

**Comment by halcy** [comment]
That would seem like a typo in the requirements file - dateutil is what we use, I'm fairly sure. I'm very busy presently, but I'll fix it soon as I get around to it (or feel free to submit a PR)

**Comment by ng-0** [comment]
Ah, cool.
I'll send a PR if you don't beat me in time, I'm busy aswell.

**Comment by ng-0** [comment]
Done in https://github.com/halcy/Mastodon.py/pull/64

**Comment by halcy** [comment]
Closed by #64
