### ISSUE TITLE
Unable to create Mastodon app due to SSL error

### ISSUE THREAD

**Issue by bpepple** [halcy/Mastodon.py#66]
Attempting to create the Mastodon app with the following code:

new_masto_app = Mastodon.create_app(
     'lastshoutapp',
     api_base_url="https://mastodon.cloud",
     to_file = 'pytooter_clientcred.txt'
)

And receive the following error:

Traceback (most recent call last):
  File "git/misc/scripts/create_mastodon_app.py", line 9, in <module>
    to_file = 'pytooter_clientcred.txt'
  File "/usr/lib/python2.7/site-packages/mastodon/Mastodon.py", line 67, in create_app
    raise MastodonNetworkError("Could not complete request: %s" % e)
mastodon.Mastodon.MastodonNetworkError: Could not complete request: HTTPSConnectionPool(host='mastodon.cloud', port=443): Max retries exceeded with url: /api/v1/apps (Caused by SSLError(SSLError(1, u'[SSL: WRONG_CURVE] wrong curve (_ssl.c:661)'),))

**Comment by halcy** [comment]
Don't think that that is an error in Mastodon.py, there's something wacky with the SSL connection here, and probably no way this library could do anything about that. You can try not using SSL, if that's acceptable for you - just use http:// instead of https:// for the endpoint.
