### ISSUE TITLE
not pep8 compliant  

### ISSUE THREAD

**Issue by foxmask** [halcy/Mastodon.py#71]
all function calls and function declarations are not pep8 compliant.
eg there is no blank before and after = signal

You can check with flake8

**Comment by halcy** [comment]
I personally do not feel strongly about style changes, to the point where if anybody wants to do initial making-everything-pep8-y I'll be glad to merge that and try to keep it clean afterwards, but I'm not about to do it myself.

**Comment by foxmask** [comment]
there is still 

```
flake8|wc -l
92
```
to fix , but 90% of them are due to the too long comment line
