### ISSUE TITLE
Simplifying code

### ISSUE THREAD

**Issue by foxmask** [halcy/Mastodon.py#72]
You can also simplify "!= None" by "is not None" or "== False" by "is False" or "if foo == True:" by "if foo:"

or here https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py#L1060-L1065 

you can do 

```python
    return self._token_expired < datetime.datetime.now()
```

You can check with pylint for example

**Comment by halcy** [comment]
(Duplicate of #71 , see there)
