### ISSUE TITLE
Servers with streaming endpoints that redirect to a different URL don't work

### ISSUE THREAD

**Issue by Elizafox** [halcy/Mastodon.py#84]
This one is tough and I don't know the best way to handle it, but...

Basically, Mastodon redirects things under /api/v1/streaming to a different URL (via 301) when configured to do so, due to the nature of various setups.

But it **only** redirects things under that endpoint, sub-endpoints like /api/v1/streaming/public return 404.

Worse still, requests strips the Authorization header when redirecting.

So, the right thing to determine the streaming endpoint:

1) Hit /api/v1/streaming to see if you get a 301 (allow_redirects=False to requests.get).
2) If you don't, you can stop here, otherwise, continue.
3) Hit the URL referenced by the Location header. This is the endpoint root.
4) All requests for the streaming server must be redirected to this URL base from now on.

I'll try to implement it, meanwhile I'm working on server-side workarounds for Mastodon.

**Comment by Elizafox** [comment]
I implemented a server-side workaround, hopefully it'll be integrated into Mastodon, but it doesn't solve the requests library stripping headers problem or issues with servers that don't have this fix.

I think I have an idea for a fix, I'll open a PR and see how it goes.

**Comment by Elizafox** [comment]
As for requests stripping the Authorization header with a redirect, this is intentional behaviour. There is unfortunately no way to turn it off.

I argue if it's going to the same domain and both source and destination are HTTPS it shouldn't do this, but I'm not sure they'll be receptive to the idea. I'll file an issue upstream about it and hopefully something can get done.

**Comment by halcy** [comment]
Merging this for now, but maybe eventually, for some use cases, there should be an interaction with the streaming URL returned with the instance info / a way to set the streaming base separately.
