### ISSUE TITLE
mastodon.Mastodon.MastodonAPIError: Encountered invalid date.

### ISSUE THREAD

**Issue by foxmask** [halcy/Mastodon.py#87]
when trying to use 
```python
token = mastodon.log_in(username=username, password=password)
```
meet the behavior :
```python
  File "lib/python3.6/site-packages/mastodon/Mastodon.py", ... in __json_date_parse
    json_object[k] = dateutil.parser.parse(v)

  File "lib/python3.6/site-packages/mastodon/Mastodon.py", ..., in __json_date_parse
    raise MastodonAPIError('Encountered invalid date.')
mastodon.Mastodon.MastodonAPIError: Encountered invalid date.
```

http://dateutil.readthedocs.io/en/stable/_modules/dateutil/parser.html#parse
in python 3 dateutil.parser.parse wait a string, and it's a timestamp that is given to dateutil

**Comment by Elizafox** [comment]
What version is your instance?

**Comment by foxmask** [comment]
I dont know 
I use the official docker image to dev with the lib and test behaviors

**Comment by halcy** [comment]
This sounds like the thing #83 fixed - are you using the newest Mastodon.py?

**Comment by foxmask** [comment]
I'll check this evening. I dont think so. Thanks

**Comment by foxmask** [comment]
v 1.1.1 looks fine .
thanks !
