### ISSUE TITLE
redirection URL is not valid

### ISSUE THREAD

**Issue by foxmask** [halcy/Mastodon.py#90]
Once I trigger the process to get the token, I redirect the user to his mastodon instance, once on the url of the mastodon instance like this one 

```
http://masto.home/oauth/authorize?client_id=69bc411afddc0a660849ba5fe04ef41a2062fccc60ca677e53a5c5b630b306b2&response_type=code&redirect_uri=https%3A%2F%2Ffoxmask.eu%2Fth%2Fcallbackmastodon%2F&scope=read+write+follow
```

(those URL are fake ; I create that @ home for dev purpose)

i'm in front of the page which tells me:

```
connected as @foxmask@masto.home
redirection URL is not valid
```

What is wrong with the redirect_uri ?

**Comment by codl** [comment]
It could be that the redirect_uri you are passing here does not match the one you passed when you registered the app (`create_app`)

**Comment by foxmask** [comment]
Hmm not bad, this detail has escaped me. I'll make a test thank

**Comment by foxmask** [comment]
it was effectivly the fact that I didnt provide the redirect_uri during the create_app .
thanks for the tips
