### ISSUE TITLE
Cannot attach more than 4 files

### ISSUE THREAD

**Issue by foxmask** [halcy/Mastodon.py#95]
Hi, 
I use Mastodon.py v 1.1.1

When I try to upload an image, I get the error in the subject.

the code is
```python
try:
    toot_media = toot_api.media_post(media_file=media, mime_type=mime_type)
    # create the post with the media id
    toot_api.status_post(content, media_ids=toot_media['id'])
except Exception as inst:
    logger.critical("Mastodon ERR {}".format(inst))
```

CRITICAL Mastodon ERR Mastodon API returned error: Validation failed: File content type is invalid, File is invalid

the error is met on that line https://github.com/halcy/Mastodon.py/blob/master/mastodon/Mastodon.py#L803

**Comment by codl** [comment]
I've been unable to reproduce this, here is [the program i've been testing with](https://gist.github.com/codl/4e4b33f122d7469a4e4a798ee43ce6c1).

The error message coming from Mastodon suggests your mimetype is incorrect or perhaps unsupported by Mastodon, what mimetype are you passing?

**Comment by foxmask** [comment]
a simple jpeg

**Comment by foxmask** [comment]
ok so now I do this 

```
       try:
            media_ids = None
           media_ids = toot_api.media_post(media_file=media)
            toot_api.status_post(content, media_ids=media_ids)
        except Exception as inst:
            logger.critical("Mastodon ERR {}".format(inst))
```
as the API says 
> media_ids can  also be the media dicts returned by media_post - they are unpacked  automatically.

and I dont provide the mime type as Mastodon find it all alone from the filename.

but this time the error is 

```
Mastodon API returned error: Cannot attach more than 4 files
```

but I handle one file :/

**Comment by codl** [comment]
`media_ids` must be a *list* of media ids or media dicts (or any iterable really). This should do the trick:

```python
toot_api.status_post(content, media_ids=[media_ids])
```

maybe documentation or the error message could be improved to make this clear

---

(i've updated [my test program](https://gist.github.com/codl/4e4b33f122d7469a4e4a798ee43ce6c1) to also post a status with the uploaded image)

**Comment by foxmask** [comment]
I could think of that , I'll test this evening 
Thank you

**Comment by foxmask** [comment]
I could not wait and test. 
Thank you, its working great
