### ISSUE TITLE
v2.0.0 compatibility?

### ISSUE THREAD

**Issue by sdukhovni** [halcy/Mastodon.py#97]
The README says that Mastodon.py is compatible with Mastodon v1.6, can we update it to deal with the bigint ID numbers in v2.0.0? Ideally Mastodon.py should return ID numbers as python integers no matter what version of Mastodon we're communicating with, and automatically convert them to/from strings as needed.

**Comment by halcy** [comment]
The "compatible with 1.6" is not a "and will forever be" type statement, so yeah, upgrading to handle 2.0.0 stuff is definitely a thing. There might also be further API updates that need to be implemented. I won't have time to do any of this until at least the 20th, though.

**Comment by codl** [comment]
as far as I can tell, the only other change in the API is that status objects now include a list of custom emojis in the status: https://github.com/tootsuite/documentation/commit/a0f77af2004554dc437b39da60938de804228087

**Comment by halcy** [comment]
All done, hopefully.
